//! The Vintage Cube card pool.
//!
//! A cube is not a set window: it is a fixed singleton list, so a format
//! built on one takes its legality from membership here rather than from the
//! sets a card was printed in. The list is a snapshot -- the MTGO Vintage
//! Cube is re-tuned between runs -- so it is recorded verbatim, sorted for
//! diffability, and dated rather than described as "current".
//!
//! Source: the MTGO Vintage Cube list published on Cube Cobra, retrieved
//! 2026-08-19. 534 cards.
//!
//! Six names in the retrieved list -- Ademi of the Silkchutes, Cren,
//! Undercity Dreamer, Goben, Gene-Splice Savant, Makdee and Itla,
//! Skysnarers, Nia, Skysail Storyteller, and Spectral Restitching -- match no
//! card Scryfall knows, by exact name or by search. Nothing authoritative
//! describes them, so they are left out rather than recorded as cards this
//! engine intends to implement; restore them here if a later snapshot
//! resolves them.

pub const VINTAGE_CUBE_POOL: &[&str] = &[
    "Abhorrent Oculus",
    "Abrade",
    "Adeline, Resplendent Cathar",
    "Aether Spellbomb",
    "Agatha's Soul Cauldron",
    "Ajani, Nacatl Pariah",
    "Amped Raptor",
    "Ancestral Recall",
    "Ancient Tomb",
    "Animate Dead",
    "Archon of Cruelty",
    "Arena of Glory",
    "Arid Mesa",
    "Arwen, Mortal Queen",
    "Astrologian's Planisphere",
    "Atraxa, Grand Unifier",
    "Avacyn's Pilgrim",
    "Badlands",
    "Balance",
    "Baleful Mastery",
    "Baleful Strix",
    "Baloth Prime",
    "Barrowgoyf",
    "Basalt Monolith",
    "Bayou",
    "Berserk",
    "Birds of Paradise",
    "Bitter Triumph",
    "Black Lotus",
    "Blackcleave Cliffs",
    "Blazemire Verge",
    "Bleachbone Verge",
    "Blightsteel Colossus",
    "Blood Crypt",
    "Bloodbraid Challenger",
    "Bloodchief's Thirst",
    "Bloodstained Mire",
    "Bloodtithe Harvester",
    "Blooming Marsh",
    "Bolas's Citadel",
    "Bone Shards",
    "Bonecrusher Giant",
    "Boseiju, Who Endures",
    "Botanical Sanctum",
    "Bountiful Landscape",
    "Brain Freeze",
    "Brainstorm",
    "Brainsurge",
    "Brazen Borrower",
    "Breeding Pool",
    "Brightglass Gearhulk",
    "Bristly Bill, Spine Sower",
    "Broadside Bombardiers",
    "Burst Lightning",
    "Cabal Ritual",
    "Candelabra of Tawnos",
    "Cankerbloom",
    "Carnage Interpreter",
    "Cathar Commando",
    "Caustic Bronco",
    "Cecil, Dark Knight",
    "Celestial Colonnade",
    "Chain Lightning",
    "Chain of Smog",
    "Chainsaw",
    "Chandra, Torch of Defiance",
    "Channel",
    "Chromatic Star",
    "Chrome Mox",
    "City of Traitors",
    "Coalition Relic",
    "Collective Brutality",
    "Commercial District",
    "Concealed Courtyard",
    "Concealing Curtains",
    "Consider",
    "Consult the Star Charts",
    "Containment Priest",
    "Copperline Gorge",
    "Cori-Steel Cutter",
    "Corpse Dance",
    "Cosmogrand Zenith",
    "Council's Judgment",
    "Counterspell",
    "Courser of Kruphix",
    "Coveted Jewel",
    "Crabomination",
    "Creeping Tar Pit",
    "Crop Rotation",
    "Crucible of Worlds",
    "Cryptic Command",
    "Currency Converter",
    "Cut Down",
    "Dack Fayden",
    "Damn",
    "Dark Confidant",
    "Dark Depths",
    "Dark Ritual",
    "Darkslick Shores",
    "Dauthi Voidwalker",
    "Daze",
    "Death-Greeter's Champion",
    "Deathrite Shaman",
    "Deep-Cavern Bat",
    "Delayed Blast Fireball",
    "Delighted Halfling",
    "Demonic Tutor",
    "Descendant of Storms",
    "Detective's Phoenix",
    "Dismember",
    "Displacer Kitten",
    "Doomsday",
    "Dragon's Rage Channeler",
    "Dreadhorde Arcanist",
    "Duelist of the Mind",
    "Duress",
    "Eagles of the North",
    "Echo of Eons",
    "Elite Spellbinder",
    "Elspeth, Knight-Errant",
    "Elspeth, Storm Slayer",
    "Elvish Mystic",
    "Elvish Reclaimer",
    "Embereth Shieldbreaker",
    "Emperor of Bones",
    "Emrakul, the Aeons Torn",
    "Emry, Lurker of the Loch",
    "Endurance",
    "Enduring Innocence",
    "Entomb",
    "Ephemerate",
    "Ertai Resurrected",
    "Esika's Chariot",
    "Etali, Primal Conqueror",
    "Eternal Witness",
    "Everflowing Chalice",
    "Exhume",
    "Expedition Map",
    "Exploration",
    "Expressive Iteration",
    "Fable of the Mirror-Breaker",
    "Fabled Passage",
    "Faerie Mastermind",
    "Faithless Looting",
    "Fallen Shinobi",
    "Fanatic of Rhonas",
    "Fastbond",
    "Fatal Push",
    "Fear of Missing Out",
    "Field of the Dead",
    "Fiery Confluence",
    "Figure of Destiny",
    "Fire Covenant",
    "Fireblast",
    "Firebolt",
    "Flame Slash",
    "Flame of Anor",
    "Flash",
    "Flickerwisp",
    "Flooded Strand",
    "Force of Negation",
    "Force of Vigor",
    "Force of Will",
    "Forensic Gadgeteer",
    "Forth Eorlingas!",
    "Fractured Identity",
    "Frantic Search",
    "Fury",
    "Gaea's Cradle",
    "Galvanic Blast",
    "Galvanic Discharge",
    "Gau, Feral Youth",
    "Generous Ent",
    "Generous Plunderer",
    "Get Lost",
    "Ghost Vacuum",
    "Gitaxian Probe",
    "Giver of Runes",
    "Glimmer Lens",
    "Glorybringer",
    "Goblin Bombardment",
    "Goblin Rabblemaster",
    "Godless Shrine",
    "Goldspan Dragon",
    "Grave Titan",
    "Green Sun's Zenith",
    "Grief",
    "Grim Monolith",
    "Griselbrand",
    "Grist, the Hunger Tide",
    "Guide of Souls",
    "Gush",
    "Gut, True Soul Zealot",
    "Hallowed Fountain",
    "Harvester of Misery",
    "Haywire Mite",
    "Headliner Scarlett",
    "Hedge Maze",
    "Hexdrinker",
    "Horizon Canopy",
    "Hullbreacher",
    "Hymn to Tourach",
    "Icetill Explorer",
    "Ignoble Hierarch",
    "Imperial Seal",
    "Indatha Triome",
    "Infernal Grasp",
    "Inquisition of Kozilek",
    "Inspiring Vantage",
    "Inti, Seneschal of the Sun",
    "Invigorate",
    "Ivora, Insatiable Heir",
    "Jace, Vryn's Prodigy",
    "Jace, Wielder of Mysteries",
    "Jace, the Mind Sculptor",
    "Jacked Rabbit",
    "Jetmir's Garden",
    "Kaito, Bane of Nightmares",
    "Kaldra Compleat",
    "Kappa Cannoneer",
    "Karakas",
    "Kari Zev, Skyship Raider",
    "Karn, Scion of Urza",
    "Keen-Eyed Curator",
    "Kellan, Planar Trailblazer",
    "Ketria Triome",
    "Kitesail Freebooter",
    "Kitsa, Otterball Elite",
    "Knight of the Reliquary",
    "Kolaghan's Command",
    "Laelia, the Blade Reforged",
    "Lavaspur Boots",
    "Ledger Shredder",
    "Legion Extruder",
    "Legolas's Quick Reflexes",
    "Leovold, Emissary of Trest",
    "Leyline Binding",
    "Library of Alexandria",
    "Life // Death",
    "Lightning Bolt",
    "Lightning Greaves",
    "Liliana of the Veil",
    "Lingering Souls",
    "Lion Sash",
    "Lion's Eye Diamond",
    "Llanowar Elves",
    "Loot, the Pathfinder",
    "Loran of the Third Path",
    "Lose Focus",
    "Lotus Cobra",
    "Lotus Petal",
    "Luminarch Aspirant",
    "Lurrus of the Dream-Den",
    "Lush Portico",
    "Lutri, the Spellchaser",
    "Lórien Revealed",
    "Magda, Brazen Outlaw",
    "Malcolm, Alluring Scoundrel",
    "Malevolent Rumble",
    "Mana Confluence",
    "Mana Crypt",
    "Mana Drain",
    "Mana Leak",
    "Mana Tithe",
    "Mana Vault",
    "Manamorphose",
    "Manifold Key",
    "Marsh Flats",
    "Memory Jar",
    "Memory Lapse",
    "Metamorphosis Fanatic",
    "Meticulous Archive",
    "Mightform Harmonizer",
    "Mind Stone",
    "Mind Twist",
    "Mine Collapse",
    "Minsc & Boo, Timeless Heroes",
    "Miscalculation",
    "Mishra's Bauble",
    "Mishra's Workshop",
    "Misty Rainforest",
    "Monstrous Rage",
    "Mother of Runes",
    "Mox Diamond",
    "Mox Emerald",
    "Mox Jet",
    "Mox Opal",
    "Mox Pearl",
    "Mox Ruby",
    "Mox Sapphire",
    "Multiversal Passage",
    "Mutagenic Growth",
    "Myr Battlesphere",
    "Mystic Confluence",
    "Mystical Tutor",
    "Nadu, Winged Wisdom",
    "Narset, Parter of Veils",
    "Natural Order",
    "Necromancy",
    "Nethergoyf",
    "Nettlecyst",
    "Night's Whisper",
    "Nissa, Who Shakes the World",
    "No More Lies",
    "Noble Hierarch",
    "Oath of Druids",
    "Occult Epiphany",
    "Ocelot Pride",
    "Oko, Thief of Crowns",
    "Oliphaunt",
    "Omnath, Locus of Creation",
    "Once Upon a Time",
    "Orcish Bowmasters",
    "Orcish Lumberjack",
    "Otawara, Soaring City",
    "Otharri, Suns' Glory",
    "Ouroboroid",
    "Oust",
    "Overgrown Tomb",
    "Overlord of the Balemurk",
    "Overlord of the Mistmoors",
    "Palace Jailer",
    "Paradoxical Outcome",
    "Parallax Wave",
    "Path to Exile",
    "Pentad Prism",
    "Pest Infestation",
    "Phantasmal Image",
    "Phelia, Exuberant Shepherd",
    "Phlage, Titan of Fire's Fury",
    "Phyrexian Metamorph",
    "Pillage the Bog",
    "Plagon, Lord of the Beach",
    "Plateau",
    "Polluted Delta",
    "Ponder",
    "Portable Hole",
    "Portal to Phyrexia",
    "Preacher of the Schism",
    "Preordain",
    "Primeval Titan",
    "Prismatic Ending",
    "Prismatic Vista",
    "Proft's Eidetic Memory",
    "Psychic Frog",
    "Pyrogoyf",
    "Pyrokinesis",
    "Quantum Riddler",
    "Questing Beast",
    "Raffine's Tower",
    "Ragavan, Nimble Pilferer",
    "Rancor",
    "Raucous Theater",
    "Raugrin Triome",
    "Razorverge Thicket",
    "Reanimate",
    "Recurring Nightmare",
    "Relic of Sauron",
    "Remand",
    "Reprieve",
    "Retrofitter Foundry",
    "Riverpyre Verge",
    "Robber of the Rich",
    "Sacred Foundry",
    "Saheeli, Sublime Artificer",
    "Savai Triome",
    "Savannah",
    "Scalding Tarn",
    "Screaming Nemesis",
    "Scrubland",
    "Scythecat Cub",
    "Seachrome Coast",
    "Seasoned Pyromancer",
    "Securitron Squadron",
    "Sedgemoor Witch",
    "Sensei's Divining Top",
    "Sentinel of the Nameless City",
    "Serra Paragon",
    "Shadowy Backstreet",
    "Shallow Grave",
    "Shelldock Isle",
    "Sheltering Landscape",
    "Sheoldred's Edict",
    "Sheoldred, the Apocalypse",
    "Shifting Woodland",
    "Shorikai, Genesis Engine",
    "Show and Tell",
    "Sink into Stupor",
    "Six",
    "Skullclamp",
    "Skyclave Apparition",
    "Slickshot Show-Off",
    "Smuggler's Copter",
    "Snapcaster Mage",
    "Sneak Attack",
    "Snuff Out",
    "Sol Ring",
    "Solitude",
    "Sorin of House Markov",
    "Soul-Guide Lantern",
    "Sowing Mycospawn",
    "Spara's Headquarters",
    "Spell Pierce",
    "Spellseeker",
    "Spirebluff Canal",
    "Springheart Nantuko",
    "Staff of the Storyteller",
    "Starting Town",
    "Static Prison",
    "Steam Vents",
    "Stern Scolding",
    "Stock Up",
    "Stomping Ground",
    "Stoneforge Mystic",
    "Stormchaser's Talent",
    "Strip Mine",
    "Subtlety",
    "Sunbaked Canyon",
    "Sunbillow Verge",
    "Sunfall",
    "Suplex",
    "Sword of the Meek",
    "Swords to Plowshares",
    "Sylvan Caryatid",
    "Sylvan Safekeeper",
    "Taiga",
    "Talisman of Conviction",
    "Talisman of Creativity",
    "Talisman of Curiosity",
    "Talisman of Dominance",
    "Talisman of Progress",
    "Talon Gates of Madara",
    "Tamiyo, Collector of Tales",
    "Tamiyo, Inquisitive Student",
    "Tarfire",
    "Tear Asunder",
    "Teferi, Hero of Dominaria",
    "Teferi, Time Raveler",
    "Temple Garden",
    "Tendrils of Agony",
    "Territorial Kavu",
    "Tersa Lightshatter",
    "Tezzeret, Cruel Captain",
    "Thalia, Guardian of Thraben",
    "Thassa's Oracle",
    "The Endstone",
    "The Mightstone and Weakstone",
    "The One Ring",
    "The Wandering Emperor",
    "Thespian's Stage",
    "Thieving Skydiver",
    "Third Path Iconoclast",
    "Thopter Foundry",
    "Thornspire Verge",
    "Thought Scour",
    "Thoughtseize",
    "Thraben Inspector",
    "Through the Breach",
    "Thundering Falls",
    "Thundertrap Trainer",
    "Tidehollow Sculler",
    "Tifa Lockhart",
    "Time Spiral",
    "Time Walk",
    "Time Warp",
    "Timetwister",
    "Tinker",
    "Tireless Tracker",
    "Tishana's Tidebinder",
    "Titania, Protector of Argoth",
    "Tolarian Academy",
    "Torsten, Founder of Benalia",
    "Touch the Spirit Realm",
    "Toxic Deluge",
    "Traveling Chocobo",
    "Treasure Cruise",
    "Trinket Mage",
    "Troll of Khazad-dûm",
    "Tropical Island",
    "Tundra",
    "Twisted Landscape",
    "Ugin, Eye of the Storms",
    "Ulvenwald Oddity",
    "Umezawa's Jitte",
    "Undercity Sewers",
    "Underground Mortuary",
    "Underground Sea",
    "Underworld Breach",
    "Unearth",
    "Unexpectedly Absent",
    "Unholy Heat",
    "Unruly Krasis",
    "Upheaval",
    "Urborg, Tomb of Yawgmoth",
    "Uro, Titan of Nature's Wrath",
    "Ursine Monstrosity",
    "Urza's Bauble",
    "Urza's Saga",
    "Urza, Lord High Artificer",
    "Vampire Hexmage",
    "Vampiric Tutor",
    "Vaultborn Tyrant",
    "Verdant Catacombs",
    "Vindicate",
    "Virtue of Loyalty",
    "Vivi Ornitier",
    "Voice of Victory",
    "Volcanic Island",
    "Voldaren Epicure",
    "Walk-In Closet // Forgotten Cellar",
    "Walking Ballista",
    "Wasteland",
    "Wastewood Verge",
    "Waterlogged Grove",
    "Watery Grave",
    "Wheel of Fortune",
    "Wight of the Reliquary",
    "Winds of Abandon",
    "Windswept Heath",
    "Wishclaw Talisman",
    "Witch Enchanter",
    "Witherbloom Apprentice",
    "Wooded Foothills",
    "Woodfall Primus",
    "Worldspine Wurm",
    "Wrath of God",
    "Wrenn and Six",
    "Xander's Lounge",
    "Yavimaya, Cradle of Growth",
    "Yawgmoth's Will",
    "Zagoth Triome",
    "Ziatora's Proving Ground",
    "Zirda, the Dawnwaker",
    "Zuran Orb",
];
