// The name one effect operation is reported under.
//
// Split out of `program_context.rs` to keep that file inside the source-size
// limit: it is a flat table with one line per effect and nothing to factor,
// so it grows with the vocabulary rather than with the rules. Included
// textually, so the imports here are that module's.

// A table that only grows: one line per effect, and nothing to factor.
#[allow(clippy::too_many_lines)]
const fn effect_operation_name(effect: EffectDef) -> &'static str {
    match effect {
        EffectDef::None => "None",
        EffectDef::Sequence(_) => "Sequence",
        EffectDef::Randomized { .. } => "Randomized",
        EffectDef::Choose(_) | EffectDef::ChooseCardName { .. } => "Choose",
        EffectDef::ForEachInBinding { .. } => "ForEachInBinding",
        EffectDef::BindMatching { .. } => "BindMatching",
        EffectDef::SelectAtRandomFromZone { .. } => "SelectAtRandomFromZone",
        EffectDef::PayOr(_) => "PayOr",
        EffectDef::SplitIntoPiles(_) => "SplitIntoPiles",
        EffectDef::PreventDamage { .. } => "PreventDamage",
        EffectDef::AddMana(_) => "AddMana",
        EffectDef::AddPlayerCounters { .. } => "AddPlayerCounters",
        EffectDef::DealDamage { .. } => "DealDamage",
        EffectDef::DealDamageFrom { .. } => "DealDamageFrom",
        EffectDef::DealDamageAndApply { .. } => "DealDamageAndApply",
        EffectDef::GainLife { .. } => "GainLife",
        EffectDef::DrawCards { .. } => "DrawCards",
        EffectDef::ShuffleLibrary { .. } => "ShuffleLibrary",
        EffectDef::BuryGraveyard { .. } => "BuryGraveyard",
        EffectDef::EmptyManaPool { .. } => "EmptyManaPool",
        EffectDef::Discard { .. } => "Discard",
        EffectDef::DiscardCards { .. } => "DiscardCards",
        EffectDef::LoseLife { .. } => "LoseLife",
        EffectDef::LoseTheGame { .. } => "LoseTheGame",
        EffectDef::WinTheGame { .. } => "WinTheGame",
        EffectDef::Tap { .. } => "Tap",
        EffectDef::RemoveFromCombat { .. } => "RemoveFromCombat",
        EffectDef::Untap { .. } => "Untap",
        EffectDef::Saddle { .. } => "Saddle",
        EffectDef::CreateToken { .. } => "CreateToken",
        EffectDef::CreateAttachedToken { .. } => "CreateAttachedToken",
        EffectDef::CreateTokenCopyOf { .. } => "CreateTokenCopyOf",
        EffectDef::Endure { .. } => "Endure",
        EffectDef::CreateMyriadTokens => "CreateMyriadTokens",
        EffectDef::Attachment(
            AttachmentDef::Attach { .. } | AttachmentDef::AttachToSource { .. },
        )
        | EffectDef::PhaseOut { .. } => "Attach",
        EffectDef::Attachment(AttachmentDef::Reconfigure { .. }) => "Reconfigure",
        EffectDef::Attachment(AttachmentDef::Unattach { .. }) => "Unattach",
        EffectDef::Attachment(AttachmentDef::PairWithSource { .. }) => "PairWithSource",
        EffectDef::Destroy { .. } => "Destroy",
        EffectDef::Detain { .. } => "Detain",
        EffectDef::Regenerate { .. } => "Regenerate",
        EffectDef::Sacrifice { .. } => "Sacrifice",
        EffectDef::SimultaneousChoose(_) => "SimultaneousChoose",
        EffectDef::SacrificeOfChoice { .. } => "SacrificeOfChoice",
        EffectDef::ExileTopOfLibraryToPlay { .. } => "ExileTopOfLibraryToPlay",
        EffectDef::ExileTopAndMayCast { .. } => "ExileTopAndMayCast",
        EffectDef::MayCastTargetWithoutPaying { .. } => "MayCastTargetWithoutPaying",
        EffectDef::Mill { .. } => "Mill",
        EffectDef::SearchZonesAndExileRest { .. } => "SearchZonesAndExileRest",
        EffectDef::MillUntil { .. } => "MillUntil",
        EffectDef::ExileFromTopUntil { .. } => "ExileFromTopUntil",
        EffectDef::ManifestDread { .. } => "ManifestDread",
        EffectDef::Cascade => "Cascade",
        EffectDef::Proliferate => "Proliferate",
        EffectDef::Explore { .. } => "Explore",
        EffectDef::LookAtHand { .. } => "LookAtHand",
        EffectDef::LookAtRandomCardInHand { .. } => "LookAtRandomCardInHand",
        EffectDef::RevealHand { .. } => "RevealHand",
        EffectDef::RevealAtRandomFromHand { .. } => "RevealAtRandomFromHand",
        EffectDef::LookAtTopAndSelect { .. } => "LookAtTopAndSelect",
        EffectDef::LookAtTopAndDistribute { .. } => "LookAtTopAndDistribute",
        EffectDef::SearchZone { .. } => "SearchZone",
        EffectDef::ChooseCards { .. } => "ChooseCards",
        EffectDef::ReplaceNextDrawThisTurn { .. } => "ReplaceNextDrawThisTurn",
        EffectDef::IfFormat { .. } => "IfFormat",
        EffectDef::Counter { .. } | EffectDef::CopyResolvingSpell { .. } => "Counter",
        EffectDef::PutSpellIntoOwnersLibrary { .. } => "PutSpellIntoOwnersLibrary",
        EffectDef::DrainLife { .. } => "DrainLife",
        EffectDef::AddManaEqualTo { .. } => "AddManaEqualTo",
        EffectDef::AddCounters { .. } => "AddCounters",
        EffectDef::RemoveCounters { .. } => "RemoveCounters",
        EffectDef::DoubleCounters { .. } => "DoubleCounters",
        EffectDef::RemoveAllCounters { .. } => "RemoveAllCounters",
        EffectDef::SkipNextUntapSteps { .. } => "SkipNextUntapSteps",
        EffectDef::ChangeTextBasicLandType { .. } => "ChangeTextBasicLandType",
        EffectDef::ChooseColor { .. } => "ChooseColor",
        EffectDef::BecomeCopyOf { .. } => "BecomeCopyOf",
        EffectDef::PutSourceOntoBattlefieldAttacking => "PutSourceOntoBattlefieldAttacking",
        EffectDef::BecomeMonarch { .. } => "BecomeMonarch",
        EffectDef::VoteForPermanentToExile { .. } => "VoteForPermanentToExile",
        EffectDef::DamageCannotBePreventedThisTurn => "DamageCannotBePreventedThisTurn",
        EffectDef::GrantFlashToNextSorcery => "GrantFlashToNextSorcery",
        EffectDef::May { .. } => "May",
        EffectDef::ExileLinkedToSource { .. } => "ExileLinkedToSource",
        EffectDef::MayPlayWithoutPaying { .. } => "MayPlayWithoutPaying",
        EffectDef::ExileGrantingOwnerPlay { .. } => "ExileGrantingOwnerPlay",
        EffectDef::ExileGrantingControllerPlayThisTurn { .. } => "ExileToPlayThisTurn",
        EffectDef::ReturnLinkedExiles { .. } => "ReturnLinkedExiles",
        EffectDef::GainControl { .. } | EffectDef::ExchangeControl { .. } => "GainControl",
        EffectDef::IfCondition { .. } => "IfCondition",
        EffectDef::InstallTrigger(_) => "InstallTrigger",
        EffectDef::CreateOngoingEffect(_) => "CreateOngoingEffect",
        EffectDef::CannotBeForcedToSacrifice => "CannotBeForcedToSacrifice",
        EffectDef::CannotBeForcedToDiscard => "CannotBeForcedToDiscard",
        EffectDef::GainClassLevel { .. } => "GainClassLevel",
        EffectDef::SubstituteBasicLandTypeUntilEndOfTurn { .. } => {
            "SubstituteBasicLandTypeUntilEndOfTurn"
        }
        EffectDef::ReduceGenericCostBy(_) => "ReduceGenericCostBy",
        EffectDef::ModifyCost(_) => "ModifyCost",
        EffectDef::CannotAttackUnless(_) => "CannotAttackUnless",
        EffectDef::CannotAttackIf(_) => "CannotAttackIf",
        EffectDef::LandwalkCanBeBlocked(_) => "LandwalkCanBeBlocked",
        EffectDef::ScheduleTurnPhases(_) => "ScheduleTurnPhases",
        EffectDef::TakeExtraTurn { .. } => "TakeExtraTurn",
        EffectDef::CreateEmblem { .. } => "CreateEmblem",
        EffectDef::PutOntoBattlefieldThen { .. } => "PutOntoBattlefieldThen",
        EffectDef::Transform { .. } => "Transform",
        EffectDef::PutIntoLibraryBeneathTop { .. } => "PutIntoLibraryBeneathTop",
        EffectDef::MoveToZone { .. } => "MoveToZone",
        EffectDef::StaticApply { .. } => "StaticApply",
        EffectDef::Apply { .. } => "Apply",
        EffectDef::Special(_) => "Special",
    }
}
