//! The Pauper Cube card pool.
//!
//! A fixed 450-card snapshot exported from Cube Cobra on 2026-08-22. Cube
//! Cobra reports that the source list was last updated on 2026-05-16. Names
//! are recorded verbatim and sorted for diffability.
//!
//! Source: <https://cubecobra.com/cube/list/5d617ac6c2a85f3b75fe95a4>

use super::super::{CUBE_RULES, CubeFormatDefinition};

pub(in crate::formats) const DEFINITION: CubeFormatDefinition = CubeFormatDefinition {
    rules: CUBE_RULES,
    cards: PAUPER_CUBE_POOL,
};

pub const PAUPER_CUBE_POOL: &[&str] = &[
    "Abrade",
    "Abraded Bluffs",
    "Abundant Harvest",
    "Accursed Marauder",
    "Aerie Auxiliary",
    "Aether Chaser",
    "Aether Poisoner",
    "Ainok Bond-Kin",
    "Ainok Wayfarer",
    "Alabaster Host Intercessor",
    "Ancestral Blade",
    "Annoyed Altisaur",
    "Arbor Elf",
    "Archaeomancer",
    "Ardent Elementalist",
    "Ardenvale Tactician",
    "Armadillo Cloak",
    "Arms of Hadar",
    "Ashes to Ashes",
    "Azorius Chancery",
    "Bannerhide Krushok",
    "Barbed Batterfist",
    "Basilisk Gate",
    "Basking Broodscale",
    "Battle Screech",
    "Beetleback Chief",
    "Behold the Multiverse",
    "Blastoderm",
    "Blessed Hippogriff",
    "Blightning",
    "Blood Aspirant",
    "Blood Fountain",
    "Bloodwater Entity",
    "Body Dropper",
    "Bogardan Dragonheart",
    "Boiling Rock Prison",
    "Bonder's Ornament",
    "Bone Picker",
    "Bonesplitter",
    "Boros Garrison",
    "Borrowed Grace",
    "Bountiful Landscape",
    "Brainstorm",
    "Bramble Wurm",
    "Brambleback Brute",
    "Branching Bolt",
    "Brimstone Volley",
    "Bristling Backwoods",
    "Burning-Tree Emissary",
    "Burst Lightning",
    "Bushwhack",
    "Candy Grapple",
    "Candy Trail",
    "Capsize",
    "Captured by Lagacs",
    "Carnophage",
    "Carrier Thrall",
    "Carrion Feeder",
    "Cast Down",
    "Cathar Commando",
    "Cavern Harpy",
    "Chain Lightning",
    "Champion of Dusan",
    "Chitin Gravestalker",
    "Cindering Cutthroat",
    "Clawing Torment",
    "Clockwork Percussionist",
    "Cloudkin Seer",
    "Coalition Honor Guard",
    "Coiling Oracle",
    "Colossal Dreadmask",
    "Conclave Naturalists",
    "Condescend",
    "Conduit Goblin",
    "Conduit Pylons",
    "Consider",
    "Contagious Vorrac",
    "Contaminated Landscape",
    "Counterspell",
    "Cradle of the Accursed",
    "Cruel Witness",
    "Cryogen Relic",
    "Cryoshatter",
    "Crypt Rats",
    "Custodi Squire",
    "Dark-Dweller Oracle",
    "Dauntless Unity",
    "Dauthi Horror",
    "Dauthi Slayer",
    "Death Denied",
    "Deceptive Landscape",
    "Deep Analysis",
    "Deftblade Elite",
    "Deluge Virtuoso",
    "Deranged Assistant",
    "Desecrator Hag",
    "Desert",
    "Dimir Aqueduct",
    "Dimir Guildmage",
    "Dinrova Horror",
    "Diregraf Horde",
    "Disfigure",
    "Displace",
    "Dog Umbra",
    "Dog Walker",
    "Doom Blade",
    "Doomed Traveler",
    "Dread Return",
    "Dreg Mangler",
    "Eagles of the North",
    "Ecstatic Awakener",
    "Eldrazi Repurposer",
    "Eldrazi Skyspawner",
    "Elite Interceptor",
    "Elite Vanguard",
    "Elvish Mystic",
    "Entourage of Trest",
    "Ephemerate",
    "Eroded Canyon",
    "Escape Tunnel",
    "Evolution Witness",
    "Exclude",
    "Expanding Ooze",
    "Experiment One",
    "Faceless Butcher",
    "Faerie Guidemother",
    "Faerie Seer",
    "Faith's Fetters",
    "Faithful Watchdog",
    "Falkenrath Noble",
    "Fanatical Firebrand",
    "Fertile Ground",
    "Fields of Strife",
    "Filigree Familiar",
    "Fireball",
    "Fireblade Artist",
    "Fireblast",
    "Firebolt",
    "Firebrand Archer",
    "Fireslinger",
    "First-Sphere Gargantua",
    "Flame Slash",
    "Flayer Husk",
    "Flesh Burrower",
    "Focus Fire",
    "Foreboding Landscape",
    "Fortress Kin-Guard",
    "Forum of Amity",
    "Frenzied Goblin",
    "Frost Trickster",
    "Furnace Strider",
    "Galvanic Discharge",
    "Generous Ent",
    "Ghostly Flicker",
    "Giant Growth",
    "Gideon's Lawkeeper",
    "Gift of Orzhova",
    "Gingerbrute",
    "Gitaxian Probe",
    "Gixian Infiltrator",
    "Glimmerlight",
    "Gnarlid Colony",
    "Gnawing Crescendo",
    "Go for the Throat",
    "Goblin Anarchomancer",
    "Goblin Bushwhacker",
    "Goblin Motivator",
    "Goblin Surprise",
    "Gods Willing",
    "Golgari Rot Farm",
    "Grapple with the Past",
    "Gravedigger",
    "Gray Merchant of Asphodel",
    "Greater Tanuki",
    "Greatsword of Tyr",
    "Grim Bauble",
    "Grim Initiate",
    "Growth Spiral",
    "Gruul Turf",
    "Guardian Idol",
    "Guardian of the Guildpact",
    "Guildsworn Prowler",
    "Gurmag Angler",
    "Guttersnipe",
    "Hard Evidence",
    "Haunted Fengraf",
    "Heliod's Pilgrim",
    "Hickory Woodlot",
    "Hidden Grotto",
    "Hissing Iguanar",
    "Homestead Courage",
    "Hooting Mandrills",
    "Hordeling Outburst",
    "Horrific Assault",
    "Imperial Oath",
    "Improvised Club",
    "Impulse",
    "Incinerate",
    "Inspiring Overseer",
    "Inspiring Paladin",
    "Into the Roil",
    "Iron Apprentice",
    "Ironhoof Boar",
    "Izzet Boilerworks",
    "Izzet Charm",
    "Jackal Pup",
    "Jade Guardian",
    "Jewel Thief",
    "Jhessian Thief",
    "Journey to Nowhere",
    "Judge's Familiar",
    "Kingpin's Pet",
    "Kor Skyfisher",
    "Krosan Tusker",
    "Kyoshi Village",
    "Leonin Bola",
    "Lightning Bolt",
    "Lightning Strike",
    "Liliana's Specter",
    "Llanowar Elves",
    "Llanowar Visionary",
    "Loathsome Curator",
    "Looter il-Kor",
    "Lose Focus",
    "Lyev Skyknight",
    "Lys Alana Informant",
    "Lórien Revealed",
    "Malevolent Rumble",
    "Man-o'-War",
    "Mana Leak",
    "Mana Tithe",
    "Mandibular Kite",
    "Mardu Skullhunter",
    "Mayhem Patrol",
    "Mechanozoa",
    "Meeting of Minds",
    "Merfolk Looter",
    "Militia Bugler",
    "Mind Stone",
    "Miner's Guidewing",
    "Mire Triton",
    "Mirrorshell Crab",
    "Miscalculation",
    "Mist Raven",
    "Mocking Sprite",
    "Mogg War Marshal",
    "Molten Gatekeeper",
    "Momentary Blink",
    "Monastery Swiftspear",
    "Monstrous Emergence",
    "Moon-Circuit Hacker",
    "Mother Bear",
    "Mulldrifter",
    "Murmuring Mystic",
    "Mutagenic Growth",
    "Mystic Sanctuary",
    "Nest Invader",
    "Nested Shambler",
    "Night Market",
    "Night's Whisper",
    "Ninja of the Deep Hours",
    "Novice Inspector",
    "Nyxborn Hydra",
    "Oblivion Ring",
    "Okiba Reckoner Raid",
    "Okiba-Gang Shinobi",
    "Oliphaunt",
    "Ominous Asylum",
    "Opt",
    "Orzhov Basilica",
    "Owlbear",
    "Palace Sentinels",
    "Paradox Gardens",
    "Peregrine Drake",
    "Perilous Landscape",
    "Perilous Myr",
    "Pestermite",
    "Pestilence",
    "Petrify",
    "Phantom Interference",
    "Phantom Nomad",
    "Phantom Tiger",
    "Pillory of the Sleepless",
    "Pinnacle Kill-Ship",
    "Plagued Rusalka",
    "Planar Disruption",
    "Plasma Bolt",
    "Ponder",
    "Porcelain Legionnaire",
    "Preening Champion",
    "Preordain",
    "Priest of Titania",
    "Prismatic Strands",
    "Pristine Talisman",
    "Prophetic Prism",
    "Pulse of Murasa",
    "Putrid Goblin",
    "Putrid Leech",
    "Quandrix Campus",
    "Quandrix Pledgemage",
    "Quicksand",
    "Raffine's Informant",
    "Raid Bombardment",
    "Raise the Alarm",
    "Rakdos Carnarium",
    "Rally at the Hornburg",
    "Rally the Peasants",
    "Ram Through",
    "Rancor",
    "Raven's Crime",
    "Reckless Charge",
    "Reckless Impulse",
    "Remove Soul",
    "Renegade Freighter",
    "Repeal",
    "Repulse",
    "Resentful Revelation",
    "Retrofitted Transmogrant",
    "Rhox Veteran",
    "Riling Dawnbreaker",
    "Rimrock Knight",
    "River Boa",
    "Rolling Thunder",
    "Rubblebelt Maverick",
    "Sagu Wildling",
    "Sakura-Tribe Elder",
    "Salt Road Packbeast",
    "Sarulf's Packmate",
    "Savage Mansion",
    "Savannah Lions",
    "Scholar of Combustion",
    "Scorched Rusalka",
    "Scoured Barrens",
    "Scrapwork Mutt",
    "Scurrilous Sentry",
    "Search Party Captain",
    "Searing Spear",
    "Seeker of the Way",
    "Seething Landscape",
    "Seize Opportunity",
    "Selesnya Sanctuary",
    "Serpent's Pass",
    "Serrated Arrows",
    "Serum Visionary",
    "Serum Visions",
    "Settle Beyond Reality",
    "Shardless Outlander",
    "Shattered Landscape",
    "Sheltering Landscape",
    "Shipwreck Dowser",
    "Shock Brigade",
    "Silver Drake",
    "Simic Growth Chamber",
    "Sinister Hideout",
    "Skewer the Critics",
    "Snakeskin Veil",
    "Snap",
    "Snapping Voidcraw",
    "Snarling Gorehound",
    "Snuff Out",
    "Soltari Trooper",
    "Soul Manipulation",
    "Sparksmith",
    "Spectacle Summit",
    "Spellbook Seeker",
    "Spelleater Wolverine",
    "Sprout Swarm",
    "Stab Wound",
    "Starbreach Whale",
    "Stormfront Pegasus",
    "Striped Riverwinder",
    "Suburban Sanctuary",
    "Sulfurous Blast",
    "Sunlance",
    "Suture Priest",
    "Sword Coast Serpent",
    "Sylvan Might",
    "Syndic of Tithes",
    "Tamiyo's Safekeeping",
    "Teetering Peaks",
    "Temperamental Oozewagg",
    "Tempest Angler",
    "Tenth District Legionnaire",
    "Territorial Hammerskull",
    "Thorn of the Black Rose",
    "Thraben Charm",
    "Thraben Inspector",
    "Thriving Grubs",
    "Titan's Grave",
    "Tithe Drinker",
    "Tithing Blade",
    "Tocasia's Dig Site",
    "Tolarian Terror",
    "Tortured Existence",
    "Tragic Slip",
    "Tranquil Cove",
    "Tranquil Landscape",
    "Trapped in the Screen",
    "Treasure Cruise",
    "Treetop Snarespinner",
    "Triplicate Spirits",
    "Troll of Khazad-dûm",
    "Trumpeting Herd",
    "Tuskeri Firewalker",
    "Twisted Landscape",
    "Ulamog's Crusher",
    "Unable to Scream",
    "Unbounded Potential",
    "Underworld Charger",
    "Underworld Rage-Hound",
    "Undying Malice",
    "Unearth",
    "University Campus",
    "Unwilling Ingredient",
    "Urban Daggertooth",
    "Utopia Sprawl",
    "Vampire Lacerator",
    "Vampire Sovereign",
    "Vault Skirge",
    "Vendetta",
    "Vermin Gorger",
    "Village Rites",
    "Vines of Vastwood",
    "Visionary's Dance",
    "Vizier of Tumbling Sands",
    "Voracious Varmint",
    "Voracious Vermin",
    "Vulshok Morningstar",
    "Wall of Roots",
    "Warship Scout",
    "Wary Farmer",
    "Weakstone's Subjugation",
    "Werebear",
    "Wild Growth",
    "Wildfire Elemental",
    "Winding Way",
    "Witch's Cottage",
    "Wither and Bloom",
    "Witherbloom Campus",
    "Witness Protection",
    "Witty Roastmaster",
    "Wolf Cove Villager",
    "Wrangle",
    "Wrenn's Resolve",
    "Writhing Chrysalis",
    "Yavimaya Elder",
    "You Hear Something on Watch",
    "You Meet in a Tavern",
    "Young Blue Dragon",
    "Zephyr Winder",
];
