//! Stable definition IDs for cards in the built-in corpus.

use crate::CardDefinitionId;

mod activation_timing;
mod attachments;
mod attack_restrictions;
mod battalion;
mod cannot_block;
mod coin_flips;
mod control_duration;
mod counted_bodies;
mod damage_dealt_by;
mod detain;
mod evolve;
mod exalted;
mod graveyard_sweep;
mod isd_rtr;
mod landwalk;
mod landwalk_blocking;
mod landwalk_followup;
mod landwalk_types;
mod premodern_regeneration;
mod prevention;
mod prevention_followup;
mod prevention_remaining;
mod rampage;
mod regeneration;
mod regeneration_followup;
mod regeneration_prohibition;
mod regeneration_remaining;
mod scavenge;
mod spore;
mod tapped_and_untap;
mod targeted_regeneration;
mod unleash;
mod wards;
pub use activation_timing::*;
pub use attachments::*;
pub use attack_restrictions::*;
pub use battalion::*;
pub use cannot_block::*;
pub use coin_flips::*;
pub use control_duration::*;
pub use counted_bodies::*;
pub use damage_dealt_by::*;
pub use detain::*;
pub use evolve::*;
pub use exalted::*;
pub use graveyard_sweep::*;
pub use isd_rtr::*;
pub use landwalk::*;
pub use landwalk_blocking::*;
pub use landwalk_followup::*;
pub use landwalk_types::*;
pub use premodern_regeneration::*;
pub use prevention::*;
pub use prevention_followup::*;
pub use prevention_remaining::*;
pub use rampage::*;
pub use regeneration::*;
pub use regeneration_followup::*;
pub use regeneration_prohibition::*;
pub use regeneration_remaining::*;
pub use scavenge::*;
pub use spore::*;
pub use tapped_and_untap::*;
pub use targeted_regeneration::*;
pub use unleash::*;
pub use wards::*;

pub const ANKH_OF_MISHRA: CardDefinitionId = CardDefinitionId(1);
pub const ATOG: CardDefinitionId = CardDefinitionId(2);
pub const BALL_LIGHTNING: CardDefinitionId = CardDefinitionId(3);
pub const BLACK_VISE: CardDefinitionId = CardDefinitionId(4);
pub const BLOOD_MOON: CardDefinitionId = CardDefinitionId(5);
pub const CHAIN_LIGHTNING: CardDefinitionId = CardDefinitionId(6);
pub const COPPER_TABLET: CardDefinitionId = CardDefinitionId(7);
pub const DETONATE: CardDefinitionId = CardDefinitionId(8);
pub const FIREBALL: CardDefinitionId = CardDefinitionId(9);
pub const FORK: CardDefinitionId = CardDefinitionId(10);
pub const GLASSES_OF_URZA: CardDefinitionId = CardDefinitionId(11);
pub const IRON_STAR: CardDefinitionId = CardDefinitionId(12);
pub const LIGHTNING_BOLT: CardDefinitionId = CardDefinitionId(13);
pub const MOUNTAIN: CardDefinitionId = CardDefinitionId(14);
pub const RED_ELEMENTAL_BLAST: CardDefinitionId = CardDefinitionId(15);
pub const SHATTER: CardDefinitionId = CardDefinitionId(16);
pub const SMOKE: CardDefinitionId = CardDefinitionId(17);
pub const STONE_GIANT: CardDefinitionId = CardDefinitionId(18);
pub const SU_CHI: CardDefinitionId = CardDefinitionId(19);
pub const WINTER_ORB: CardDefinitionId = CardDefinitionId(20);
pub const BLACK_LOTUS: CardDefinitionId = CardDefinitionId(21);
pub const CHAOS_ORB: CardDefinitionId = CardDefinitionId(22);
pub const DRAGON_WHELP: CardDefinitionId = CardDefinitionId(23);
pub const GOBLIN_BALLOON_BRIGADE: CardDefinitionId = CardDefinitionId(24);
pub const GOBLIN_DIGGING_TEAM: CardDefinitionId = CardDefinitionId(25);
pub const GOBLIN_GRENADE: CardDefinitionId = CardDefinitionId(26);
pub const GOBLIN_KING: CardDefinitionId = CardDefinitionId(27);
pub const GOBLINS_OF_THE_FLARG: CardDefinitionId = CardDefinitionId(28);
pub const GRANITE_GARGOYLE: CardDefinitionId = CardDefinitionId(29);
pub const IRONCLAW_ORCS: CardDefinitionId = CardDefinitionId(30);
pub const MISHRA_S_FACTORY: CardDefinitionId = CardDefinitionId(31);
pub const MOX_EMERALD: CardDefinitionId = CardDefinitionId(32);
pub const MOX_JET: CardDefinitionId = CardDefinitionId(33);
pub const MOX_PEARL: CardDefinitionId = CardDefinitionId(34);
pub const MOX_RUBY: CardDefinitionId = CardDefinitionId(35);
pub const MOX_SAPPHIRE: CardDefinitionId = CardDefinitionId(36);
pub const ORCISH_MECHANICS: CardDefinitionId = CardDefinitionId(37);
pub const SOL_RING: CardDefinitionId = CardDefinitionId(38);
pub const STRIP_MINE: CardDefinitionId = CardDefinitionId(39);
pub const WHEEL_OF_FORTUNE: CardDefinitionId = CardDefinitionId(40);
pub const JUGGERNAUT: CardDefinitionId = CardDefinitionId(41);
pub const MANA_VAULT: CardDefinitionId = CardDefinitionId(42);
pub const TRISKELION: CardDefinitionId = CardDefinitionId(43);
pub const ANCESTRAL_RECALL: CardDefinitionId = CardDefinitionId(44);
pub const BRAINGEYSER: CardDefinitionId = CardDefinitionId(45);
pub const COUNTERSPELL: CardDefinitionId = CardDefinitionId(46);
pub const DISENCHANT: CardDefinitionId = CardDefinitionId(47);
pub const FELLWAR_STONE: CardDefinitionId = CardDefinitionId(48);
pub const ISLAND: CardDefinitionId = CardDefinitionId(49);
pub const IVORY_TOWER: CardDefinitionId = CardDefinitionId(50);
pub const JAYEMDAE_TOME: CardDefinitionId = CardDefinitionId(51);
pub const PLAINS: CardDefinitionId = CardDefinitionId(52);
pub const SERRA_ANGEL: CardDefinitionId = CardDefinitionId(53);
pub const SWORDS_TO_PLOWSHARES: CardDefinitionId = CardDefinitionId(54);
pub const TIME_WALK: CardDefinitionId = CardDefinitionId(55);
pub const TUNDRA: CardDefinitionId = CardDefinitionId(56);
pub const VOLCANIC_ISLAND: CardDefinitionId = CardDefinitionId(57);
pub const ARMAGEDDON: CardDefinitionId = CardDefinitionId(58);
pub const BADLANDS: CardDefinitionId = CardDefinitionId(59);
pub const BALANCE: CardDefinitionId = CardDefinitionId(60);
pub const BAYOU: CardDefinitionId = CardDefinitionId(61);
pub const BLACK_KNIGHT: CardDefinitionId = CardDefinitionId(62);
pub const BIRDS_OF_PARADISE: CardDefinitionId = CardDefinitionId(63);
pub const BLUE_ELEMENTAL_BLAST: CardDefinitionId = CardDefinitionId(64);
pub const CHANNEL: CardDefinitionId = CardDefinitionId(65);
pub const CITY_OF_BRASS: CardDefinitionId = CardDefinitionId(66);
pub const CRUSADE: CardDefinitionId = CardDefinitionId(67);
pub const DARK_RITUAL: CardDefinitionId = CardDefinitionId(68);
pub const DEMONIC_TUTOR: CardDefinitionId = CardDefinitionId(69);
pub const DIVINE_OFFERING: CardDefinitionId = CardDefinitionId(70);
pub const DRAIN_LIFE: CardDefinitionId = CardDefinitionId(71);
pub const EARTHQUAKE: CardDefinitionId = CardDefinitionId(72);
pub const ERHNAM_DJINN: CardDefinitionId = CardDefinitionId(73);
pub const FOREST: CardDefinitionId = CardDefinitionId(74);
pub const HYMN_TO_TOURACH: CardDefinitionId = CardDefinitionId(75);
pub const HYPNOTIC_SPECTER: CardDefinitionId = CardDefinitionId(76);
pub const ICATIAN_JAVELINEERS: CardDefinitionId = CardDefinitionId(77);
pub const JUZAM_DJINN: CardDefinitionId = CardDefinitionId(78);
pub const LIBRARY_OF_ALEXANDRIA: CardDefinitionId = CardDefinitionId(79);
pub const MANA_DRAIN: CardDefinitionId = CardDefinitionId(80);
pub const MAZE_OF_ITH: CardDefinitionId = CardDefinitionId(81);
pub const MIND_TWIST: CardDefinitionId = CardDefinitionId(82);
pub const MISHRA_S_WORKSHOP: CardDefinitionId = CardDefinitionId(83);
pub const NEVINYRRALS_DISK: CardDefinitionId = CardDefinitionId(84);
pub const ORDER_OF_LEITBUR: CardDefinitionId = CardDefinitionId(85);
pub const ORDER_OF_THE_EBON_HAND: CardDefinitionId = CardDefinitionId(86);
pub const PLATEAU: CardDefinitionId = CardDefinitionId(87);
pub const PSIONIC_BLAST: CardDefinitionId = CardDefinitionId(88);
pub const RECALL: CardDefinitionId = CardDefinitionId(89);
pub const REGROWTH: CardDefinitionId = CardDefinitionId(90);
pub const SAVANNAH: CardDefinitionId = CardDefinitionId(91);
pub const SAVANNAH_LIONS: CardDefinitionId = CardDefinitionId(92);
pub const SCRUBLAND: CardDefinitionId = CardDefinitionId(93);
pub const SERENDIB_EFREET: CardDefinitionId = CardDefinitionId(94);
pub const SENGIR_VAMPIRE: CardDefinitionId = CardDefinitionId(95);
pub const SINKHOLE: CardDefinitionId = CardDefinitionId(96);
pub const SWAMP: CardDefinitionId = CardDefinitionId(97);
pub const SYLVAN_LIBRARY: CardDefinitionId = CardDefinitionId(98);
pub const TAIGA: CardDefinitionId = CardDefinitionId(99);
pub const TERROR: CardDefinitionId = CardDefinitionId(100);
pub const THUNDER_SPIRIT: CardDefinitionId = CardDefinitionId(101);
pub const TIME_VAULT: CardDefinitionId = CardDefinitionId(102);
pub const TIMETWISTER: CardDefinitionId = CardDefinitionId(103);
pub const TROPICAL_ISLAND: CardDefinitionId = CardDefinitionId(104);
pub const UNDERGROUND_SEA: CardDefinitionId = CardDefinitionId(105);
pub const WHIRLING_DERVISH: CardDefinitionId = CardDefinitionId(106);
pub const WHITE_KNIGHT: CardDefinitionId = CardDefinitionId(107);
pub const ARGOTHIAN_PIXIES: CardDefinitionId = CardDefinitionId(108);
pub const BERSERK: CardDefinitionId = CardDefinitionId(109);
pub const CITY_IN_A_BOTTLE: CardDefinitionId = CardDefinitionId(110);
pub const COPY_ARTIFACT: CardDefinitionId = CardDefinitionId(111);
pub const DUST_TO_DUST: CardDefinitionId = CardDefinitionId(112);
pub const ENERGY_FLUX: CardDefinitionId = CardDefinitionId(113);
pub const GIANT_GROWTH: CardDefinitionId = CardDefinitionId(114);
pub const HURKYLS_RECALL: CardDefinitionId = CardDefinitionId(115);
pub const ICY_MANIPULATOR: CardDefinitionId = CardDefinitionId(116);
pub const KIRD_APE: CardDefinitionId = CardDefinitionId(117);
pub const LLANOWAR_ELVES: CardDefinitionId = CardDefinitionId(118);
pub const MOAT: CardDefinitionId = CardDefinitionId(119);
pub const PENDELHAVEN: CardDefinitionId = CardDefinitionId(120);
pub const RELIC_BARRIER: CardDefinitionId = CardDefinitionId(121);
pub const SAGE_OF_LAT_NAM: CardDefinitionId = CardDefinitionId(122);
pub const SEDGE_TROLL: CardDefinitionId = CardDefinitionId(123);
pub const SCRYB_SPRITES: CardDefinitionId = CardDefinitionId(124);
pub const STONE_RAIN: CardDefinitionId = CardDefinitionId(125);
pub const TETRAVUS: CardDefinitionId = CardDefinitionId(126);
pub const THE_ABYSS: CardDefinitionId = CardDefinitionId(127);
pub const WRATH_OF_GOD: CardDefinitionId = CardDefinitionId(128);
pub const ABRUPT_DECAY: CardDefinitionId = CardDefinitionId(129);
pub const AETHERLING: CardDefinitionId = CardDefinitionId(130);
pub const ANGEL_OF_SERENITY: CardDefinitionId = CardDefinitionId(131);
pub const ARBOR_ELF: CardDefinitionId = CardDefinitionId(132);
pub const ARCHANGEL_OF_THUNE: CardDefinitionId = CardDefinitionId(133);
pub const ASSEMBLE_THE_LEGION: CardDefinitionId = CardDefinitionId(134);
pub const AUGUR_OF_BOLAS: CardDefinitionId = CardDefinitionId(135);
pub const AURELIAS_FURY: CardDefinitionId = CardDefinitionId(136);
pub const AURELIA_THE_WARLEADER: CardDefinitionId = CardDefinitionId(137);
pub const AVACYNS_PILGRIM: CardDefinitionId = CardDefinitionId(138);
pub const AZORIUS_CHARM: CardDefinitionId = CardDefinitionId(139);
pub const BLASPHEMOUS_ACT: CardDefinitionId = CardDefinitionId(140);
pub const BLIND_OBEDIENCE: CardDefinitionId = CardDefinitionId(141);
pub const BLOOD_BARON_OF_VIZKOPA: CardDefinitionId = CardDefinitionId(142);
pub const BONFIRE_OF_THE_DAMNED: CardDefinitionId = CardDefinitionId(143);
pub const BOROS_CHARM: CardDefinitionId = CardDefinitionId(144);
pub const BOROS_RECKONER: CardDefinitionId = CardDefinitionId(145);
pub const BURNING_EARTH: CardDefinitionId = CardDefinitionId(146);
pub const CAVERN_OF_SOULS: CardDefinitionId = CardDefinitionId(147);
pub const CELESTIAL_FLARE: CardDefinitionId = CardDefinitionId(148);
pub const CLIFFTOP_RETREAT: CardDefinitionId = CardDefinitionId(149);
pub const COUNTERFLUX: CardDefinitionId = CardDefinitionId(150);
pub const DEMONIC_RISING: CardDefinitionId = CardDefinitionId(151);
pub const DESECRATION_DEMON: CardDefinitionId = CardDefinitionId(152);
pub const DETENTION_SPHERE: CardDefinitionId = CardDefinitionId(153);
pub const DISCIPLE_OF_BOLAS: CardDefinitionId = CardDefinitionId(154);
pub const DISPEL: CardDefinitionId = CardDefinitionId(155);
pub const DISSIPATE: CardDefinitionId = CardDefinitionId(156);
pub const DOMRI_RADE: CardDefinitionId = CardDefinitionId(157);
pub const DOOM_BLADE: CardDefinitionId = CardDefinitionId(158);
pub const DURESS: CardDefinitionId = CardDefinitionId(159);
pub const ELVISH_MYSTIC: CardDefinitionId = CardDefinitionId(160);
pub const ENCROACHING_WASTES: CardDefinitionId = CardDefinitionId(161);
pub const ESSENCE_SCATTER: CardDefinitionId = CardDefinitionId(162);
pub const FLAMES_OF_THE_FIREBRAND: CardDefinitionId = CardDefinitionId(163);
pub const FLINTHOOF_BOAR: CardDefinitionId = CardDefinitionId(164);
pub const GARRUK_RELENTLESS: CardDefinitionId = CardDefinitionId(165);
pub const GAVONY_TOWNSHIP: CardDefinitionId = CardDefinitionId(166);
pub const GAZE_OF_GRANITE: CardDefinitionId = CardDefinitionId(167);
pub const GHOR_CLAN_RAMPAGER: CardDefinitionId = CardDefinitionId(168);
pub const GHOST_QUARTER: CardDefinitionId = CardDefinitionId(169);
pub const GLACIAL_FORTRESS: CardDefinitionId = CardDefinitionId(170);
pub const GODLESS_SHRINE: CardDefinitionId = CardDefinitionId(171);
pub const GOLGARI_GUILDGATE: CardDefinitionId = CardDefinitionId(172);
pub const GRISLY_SALVAGE: CardDefinitionId = CardDefinitionId(173);
pub const HALLOWED_FOUNTAIN: CardDefinitionId = CardDefinitionId(174);
pub const HELLRIDER: CardDefinitionId = CardDefinitionId(175);
pub const HUNTMASTER_OF_THE_FELLS: CardDefinitionId = CardDefinitionId(176);
pub const ISOLATED_CHAPEL: CardDefinitionId = CardDefinitionId(177);
pub const IZZET_CHARM: CardDefinitionId = CardDefinitionId(178);
pub const IZZET_STATICASTER: CardDefinitionId = CardDefinitionId(179);
pub const JACE_ARCHITECT_OF_THOUGHT: CardDefinitionId = CardDefinitionId(180);
pub const JACE_MEMORY_ADEPT: CardDefinitionId = CardDefinitionId(181);
pub const KESSIG_WOLF_RUN: CardDefinitionId = CardDefinitionId(182);
pub const LIFEBANE_ZOMBIE: CardDefinitionId = CardDefinitionId(183);
pub const LILIANA_OF_THE_VEIL: CardDefinitionId = CardDefinitionId(184);
pub const LOXODON_SMITER: CardDefinitionId = CardDefinitionId(185);
pub const MIZZIUM_MORTARS: CardDefinitionId = CardDefinitionId(186);
pub const MOORLAND_HAUNT: CardDefinitionId = CardDefinitionId(187);
pub const MULCH: CardDefinitionId = CardDefinitionId(188);
pub const MUTAVAULT: CardDefinitionId = CardDefinitionId(189);
pub const MUTILATE: CardDefinitionId = CardDefinitionId(190);
pub const NEGATE: CardDefinitionId = CardDefinitionId(191);
pub const OBLIVION_RING: CardDefinitionId = CardDefinitionId(192);
pub const OBZEDAT_GHOST_COUNCIL: CardDefinitionId = CardDefinitionId(193);
pub const OVERGROWN_TOMB: CardDefinitionId = CardDefinitionId(194);
pub const PILLAR_OF_FLAME: CardDefinitionId = CardDefinitionId(195);
pub const PITHING_NEEDLE: CardDefinitionId = CardDefinitionId(196);
pub const PRIMEVAL_BOUNTY: CardDefinitionId = CardDefinitionId(197);
pub const PUTREFY: CardDefinitionId = CardDefinitionId(198);
pub const QUICKEN: CardDefinitionId = CardDefinitionId(199);
pub const RATCHET_BOMB: CardDefinitionId = CardDefinitionId(200);
pub const RAY_OF_REVELATION: CardDefinitionId = CardDefinitionId(201);
pub const REST_IN_PEACE: CardDefinitionId = CardDefinitionId(202);
pub const RESTORATION_ANGEL: CardDefinitionId = CardDefinitionId(203);
pub const RHOX_FAITHMENDER: CardDefinitionId = CardDefinitionId(204);
pub const ROOTBOUND_CRAG: CardDefinitionId = CardDefinitionId(205);
pub const RURIC_THAR_THE_UNBOWED: CardDefinitionId = CardDefinitionId(206);
pub const SACRED_FOUNDRY: CardDefinitionId = CardDefinitionId(207);
pub const SCAVENGING_OOZE: CardDefinitionId = CardDefinitionId(208);
pub const SELESNYA_CHARM: CardDefinitionId = CardDefinitionId(209);
pub const SEPULCHRAL_PRIMORDIAL: CardDefinitionId = CardDefinitionId(210);
pub const SHADOWBORN_DEMON: CardDefinitionId = CardDefinitionId(211);
pub const SIGARDA_HOST_OF_HERONS: CardDefinitionId = CardDefinitionId(212);
pub const SIGN_IN_BLOOD: CardDefinitionId = CardDefinitionId(213);
pub const SIN_COLLECTOR: CardDefinitionId = CardDefinitionId(214);
pub const SNAPCASTER_MAGE: CardDefinitionId = CardDefinitionId(215);
pub const SPHINXS_REVELATION: CardDefinitionId = CardDefinitionId(216);
pub const STEAM_VENTS: CardDefinitionId = CardDefinitionId(217);
pub const STOMPING_GROUND: CardDefinitionId = CardDefinitionId(218);
pub const STRANGLEROOT_GEIST: CardDefinitionId = CardDefinitionId(219);
pub const SULFUR_FALLS: CardDefinitionId = CardDefinitionId(220);
pub const SUNPETAL_GROVE: CardDefinitionId = CardDefinitionId(221);
pub const SUPREME_VERDICT: CardDefinitionId = CardDefinitionId(222);
pub const SYNCOPATE: CardDefinitionId = CardDefinitionId(223);
pub const TEMPLE_GARDEN: CardDefinitionId = CardDefinitionId(224);
pub const TERMINUS: CardDefinitionId = CardDefinitionId(225);
pub const THINK_TWICE: CardDefinitionId = CardDefinitionId(226);
pub const THRAGTUSK: CardDefinitionId = CardDefinitionId(227);
pub const THUNDERMAW_HELLKITE: CardDefinitionId = CardDefinitionId(228);
pub const TRAGIC_SLIP: CardDefinitionId = CardDefinitionId(229);
pub const TURN_BURN: CardDefinitionId = CardDefinitionId(230);
pub const ULTIMATE_PRICE: CardDefinitionId = CardDefinitionId(231);
pub const UNBURIAL_RITES: CardDefinitionId = CardDefinitionId(232);
pub const UNDERWORLD_CONNECTIONS: CardDefinitionId = CardDefinitionId(233);
pub const UNFLINCHING_COURAGE: CardDefinitionId = CardDefinitionId(234);
pub const URGENT_EXORCISM: CardDefinitionId = CardDefinitionId(235);
pub const VAMPIRE_NIGHTHAWK: CardDefinitionId = CardDefinitionId(236);
pub const VAULT_OF_THE_ARCHANGEL: CardDefinitionId = CardDefinitionId(237);
pub const VOICE_OF_RESURGENCE: CardDefinitionId = CardDefinitionId(238);
pub const VOLCANIC_STRENGTH: CardDefinitionId = CardDefinitionId(239);
pub const VRASKA_THE_UNSEEN: CardDefinitionId = CardDefinitionId(240);
pub const WAR_PRIEST_OF_THUNE: CardDefinitionId = CardDefinitionId(241);
pub const WARLEADERS_HELIX: CardDefinitionId = CardDefinitionId(242);
pub const WOODLAND_CEMETERY: CardDefinitionId = CardDefinitionId(243);
pub const ZEALOUS_CONSCRIPTS: CardDefinitionId = CardDefinitionId(244);

/// Token definitions. Tokens are game objects rather than printed cards; they
/// live in the catalog so a client can look one up by definition, and belong
/// to no set any format allows, so they are never deck-legal.
pub const BEAST_TOKEN_3_3_GREEN: CardDefinitionId = CardDefinitionId(245);
pub const KNIGHT_TOKEN_2_2_WHITE: CardDefinitionId = CardDefinitionId(246);
pub const SOLDIER_TOKEN_1_1_RED_WHITE: CardDefinitionId = CardDefinitionId(247);

/// Definition ids are a wire contract, so they are only ever appended. A card
/// added to an older set therefore lands after the tokens rather than beside
/// its set's block.
pub const WALL_OF_STONE: CardDefinitionId = CardDefinitionId(248);
pub const DEMON_TOKEN_5_5_BLACK: CardDefinitionId = CardDefinitionId(249);
pub const MAGICAL_HACK: CardDefinitionId = CardDefinitionId(250);
pub const THESPIANS_STAGE: CardDefinitionId = CardDefinitionId(251);
pub const DRYAD_ARBOR: CardDefinitionId = CardDefinitionId(252);
pub const NYLEAS_PRESENCE: CardDefinitionId = CardDefinitionId(253);
pub const ELEMENTAL_TOKEN_GREEN_WHITE: CardDefinitionId = CardDefinitionId(254);
pub const SPIRIT_TOKEN_1_1_WHITE: CardDefinitionId = CardDefinitionId(255);
pub const WOLF_TOKEN_2_2_GREEN: CardDefinitionId = CardDefinitionId(256);
pub const WOLF_TOKEN_1_1_BLACK: CardDefinitionId = CardDefinitionId(257);
pub const DOMRI_RADE_EMBLEM: CardDefinitionId = CardDefinitionId(258);
pub const TETRAVITE_TOKEN: CardDefinitionId = CardDefinitionId(259);
pub const ASSASSIN_TOKEN_1_1_BLACK: CardDefinitionId = CardDefinitionId(260);
pub const URBORG_TOMB_OF_YAWGMOTH: CardDefinitionId = CardDefinitionId(261);
pub const YAVIMAYA_CRADLE_OF_GROWTH: CardDefinitionId = CardDefinitionId(262);
pub const DARKSTEEL_INGOT: CardDefinitionId = CardDefinitionId(263);
pub const HYDROBLAST: CardDefinitionId = CardDefinitionId(264);
pub const INCINERATE: CardDefinitionId = CardDefinitionId(265);
pub const PYROBLAST: CardDefinitionId = CardDefinitionId(266);
pub const JACKAL_PUP: CardDefinitionId = CardDefinitionId(267);
pub const MOGG_FANATIC: CardDefinitionId = CardDefinitionId(268);
pub const SEAL_OF_FIRE: CardDefinitionId = CardDefinitionId(269);
pub const NATURALIZE: CardDefinitionId = CardDefinitionId(270);
pub const LOTUS_PETAL: CardDefinitionId = CardDefinitionId(271);
pub const MANA_LEAK: CardDefinitionId = CardDefinitionId(272);
pub const VOLCANIC_HAMMER: CardDefinitionId = CardDefinitionId(273);
pub const MONK_REALIST: CardDefinitionId = CardDefinitionId(274);
pub const ANNUL: CardDefinitionId = CardDefinitionId(275);
pub const SEAL_OF_CLEANSING: CardDefinitionId = CardDefinitionId(276);
pub const FACT_OR_FICTION: CardDefinitionId = CardDefinitionId(277);
pub const VINDICATE: CardDefinitionId = CardDefinitionId(278);
pub const WASTELAND: CardDefinitionId = CardDefinitionId(279);
pub const DUST_BOWL: CardDefinitionId = CardDefinitionId(280);
pub const RISHADAN_PORT: CardDefinitionId = CardDefinitionId(281);
pub const COASTAL_TOWER: CardDefinitionId = CardDefinitionId(282);
pub const FLOODED_STRAND: CardDefinitionId = CardDefinitionId(283);
pub const WOODED_FOOTHILLS: CardDefinitionId = CardDefinitionId(284);
pub const TRANQUIL_DOMAIN: CardDefinitionId = CardDefinitionId(285);
pub const WARMTH: CardDefinitionId = CardDefinitionId(286);
pub const ROOT_MAZE: CardDefinitionId = CardDefinitionId(287);
pub const CLAWS_OF_GIX: CardDefinitionId = CardDefinitionId(288);
pub const PHYREXIAN_ARENA: CardDefinitionId = CardDefinitionId(289);
pub const UPHEAVAL: CardDefinitionId = CardDefinitionId(290);
pub const QUIRION_DRYAD: CardDefinitionId = CardDefinitionId(291);
pub const GOBLIN_SHARPSHOOTER: CardDefinitionId = CardDefinitionId(292);
pub const SYLVAN_SAFEKEEPER: CardDefinitionId = CardDefinitionId(293);
pub const ADARKAR_WASTES: CardDefinitionId = CardDefinitionId(294);
pub const KARPLUSAN_FOREST: CardDefinitionId = CardDefinitionId(295);
pub const UNDERGROUND_RIVER: CardDefinitionId = CardDefinitionId(296);
pub const CAVES_OF_KOILOS: CardDefinitionId = CardDefinitionId(297);
pub const LLANOWAR_WASTES: CardDefinitionId = CardDefinitionId(298);
pub const YAVIMAYA_COAST: CardDefinitionId = CardDefinitionId(299);
pub const ANCIENT_TOMB: CardDefinitionId = CardDefinitionId(300);
pub const MANA_SHORT: CardDefinitionId = CardDefinitionId(301);
pub const STASIS: CardDefinitionId = CardDefinitionId(302);
pub const PRESENCE_OF_THE_MASTER: CardDefinitionId = CardDefinitionId(303);
pub const TORMODS_CRYPT: CardDefinitionId = CardDefinitionId(304);
pub const REANIMATE: CardDefinitionId = CardDefinitionId(305);
pub const FIRE_ICE: CardDefinitionId = CardDefinitionId(306);
pub const GOBLIN_PYROMANCER: CardDefinitionId = CardDefinitionId(307);
pub const KOR_HAVEN: CardDefinitionId = CardDefinitionId(308);
pub const TSABOS_WEB: CardDefinitionId = CardDefinitionId(309);
pub const IMPULSE: CardDefinitionId = CardDefinitionId(310);
pub const SLEIGHT_OF_HAND: CardDefinitionId = CardDefinitionId(311);
pub const OPT: CardDefinitionId = CardDefinitionId(312);
pub const ENLIGHTENED_TUTOR: CardDefinitionId = CardDefinitionId(313);
pub const WORLDLY_TUTOR: CardDefinitionId = CardDefinitionId(314);
pub const BLESSING: CardDefinitionId = CardDefinitionId(315);
pub const CONVERSION: CardDefinitionId = CardDefinitionId(316);
pub const HOLY_ARMOR: CardDefinitionId = CardDefinitionId(317);
pub const HOLY_STRENGTH: CardDefinitionId = CardDefinitionId(318);
pub const KARMA: CardDefinitionId = CardDefinitionId(319);
pub const LANCE: CardDefinitionId = CardDefinitionId(320);
pub const NORTHERN_PALADIN: CardDefinitionId = CardDefinitionId(321);
pub const PEARLED_UNICORN: CardDefinitionId = CardDefinitionId(322);
pub const RESURRECTION: CardDefinitionId = CardDefinitionId(323);
pub const RIGHTEOUSNESS: CardDefinitionId = CardDefinitionId(324);
pub const WALL_OF_SWORDS: CardDefinitionId = CardDefinitionId(325);
pub const AIR_ELEMENTAL: CardDefinitionId = CardDefinitionId(326);
pub const CLONE: CardDefinitionId = CardDefinitionId(327);
pub const FLIGHT: CardDefinitionId = CardDefinitionId(328);
pub const INVISIBILITY: CardDefinitionId = CardDefinitionId(329);
pub const JUMP: CardDefinitionId = CardDefinitionId(330);
pub const LIFETAP: CardDefinitionId = CardDefinitionId(331);
pub const MAHAMOTI_DJINN: CardDefinitionId = CardDefinitionId(332);
pub const MERFOLK_OF_THE_PEARL_TRIDENT: CardDefinitionId = CardDefinitionId(333);
pub const PHANTASMAL_FORCES: CardDefinitionId = CardDefinitionId(334);
pub const PHANTOM_MONSTER: CardDefinitionId = CardDefinitionId(335);
pub const PRODIGAL_SORCERER: CardDefinitionId = CardDefinitionId(336);
pub const SPELL_BLAST: CardDefinitionId = CardDefinitionId(337);
pub const TWIDDLE: CardDefinitionId = CardDefinitionId(338);
pub const UNSUMMON: CardDefinitionId = CardDefinitionId(339);
pub const WALL_OF_AIR: CardDefinitionId = CardDefinitionId(340);
pub const WALL_OF_WATER: CardDefinitionId = CardDefinitionId(341);
pub const WATER_ELEMENTAL: CardDefinitionId = CardDefinitionId(342);
pub const BAD_MOON: CardDefinitionId = CardDefinitionId(343);
pub const DEATHGRIP: CardDefinitionId = CardDefinitionId(344);
pub const EVIL_PRESENCE: CardDefinitionId = CardDefinitionId(345);
pub const FEAR: CardDefinitionId = CardDefinitionId(346);
pub const FROZEN_SHADE: CardDefinitionId = CardDefinitionId(347);
pub const HOWL_FROM_BEYOND: CardDefinitionId = CardDefinitionId(348);
pub const PESTILENCE: CardDefinitionId = CardDefinitionId(349);
pub const RAISE_DEAD: CardDefinitionId = CardDefinitionId(350);
pub const SCATHE_ZOMBIES: CardDefinitionId = CardDefinitionId(351);
pub const UNHOLY_STRENGTH: CardDefinitionId = CardDefinitionId(352);
pub const WEAKNESS: CardDefinitionId = CardDefinitionId(353);
pub const ARMY_OF_ALLAH: CardDefinitionId = CardDefinitionId(354);
pub const KING_SULEIMAN: CardDefinitionId = CardDefinitionId(355);
pub const MOORISH_CAVALRY: CardDefinitionId = CardDefinitionId(356);
pub const PIETY: CardDefinitionId = CardDefinitionId(357);
pub const REPENTANT_BLACKSMITH: CardDefinitionId = CardDefinitionId(358);
pub const FLYING_MEN: CardDefinitionId = CardDefinitionId(359);
pub const HASRAN_OGRESS: CardDefinitionId = CardDefinitionId(360);
pub const JUNUN_EFREET: CardDefinitionId = CardDefinitionId(361);
pub const STONE_THROWING_DEVILS: CardDefinitionId = CardDefinitionId(362);
pub const ALI_BABA: CardDefinitionId = CardDefinitionId(363);
pub const BIRD_MAIDEN: CardDefinitionId = CardDefinitionId(364);
pub const DESERT_TWISTER: CardDefinitionId = CardDefinitionId(365);
pub const SANDSTORM: CardDefinitionId = CardDefinitionId(366);
pub const WYLULI_WOLF: CardDefinitionId = CardDefinitionId(367);
pub const ALADDINS_RING: CardDefinitionId = CardDefinitionId(368);
pub const BRASS_MAN: CardDefinitionId = CardDefinitionId(369);
pub const DANCING_SCIMITAR: CardDefinitionId = CardDefinitionId(370);
pub const EBONY_HORSE: CardDefinitionId = CardDefinitionId(371);
pub const FLYING_CARPET: CardDefinitionId = CardDefinitionId(372);
pub const JANDORS_SADDLEBAGS: CardDefinitionId = CardDefinitionId(373);
pub const BAZAAR_OF_BAGHDAD: CardDefinitionId = CardDefinitionId(374);
pub const ARGIVIAN_ARCHAEOLOGIST: CardDefinitionId = CardDefinitionId(375);
pub const RECONSTRUCTION: CardDefinitionId = CardDefinitionId(376);
pub const ARTIFACT_BLAST: CardDefinitionId = CardDefinitionId(377);
pub const SHATTERSTORM: CardDefinitionId = CardDefinitionId(378);
pub const CITANUL_DRUID: CardDefinitionId = CardDefinitionId(379);
pub const CRUMBLE: CardDefinitionId = CardDefinitionId(380);
pub const DRAGON_ENGINE: CardDefinitionId = CardDefinitionId(381);
pub const GOLGOTHIAN_SYLEX: CardDefinitionId = CardDefinitionId(382);
pub const GRAPESHOT_CATAPULT: CardDefinitionId = CardDefinitionId(383);
pub const JALUM_TOME: CardDefinitionId = CardDefinitionId(384);
pub const MIGHTSTONE: CardDefinitionId = CardDefinitionId(385);
pub const MILLSTONE: CardDefinitionId = CardDefinitionId(386);
pub const OBELISK_OF_UNDOING: CardDefinitionId = CardDefinitionId(387);
pub const ONULET: CardDefinitionId = CardDefinitionId(388);
pub const ORNITHOPTER: CardDefinitionId = CardDefinitionId(389);
pub const STAFF_OF_ZEGON: CardDefinitionId = CardDefinitionId(390);
pub const TABLET_OF_EPITYR: CardDefinitionId = CardDefinitionId(391);
pub const TAWNOSS_WAND: CardDefinitionId = CardDefinitionId(392);
pub const URZAS_CHALICE: CardDefinitionId = CardDefinitionId(393);
pub const WALL_OF_SPEARS: CardDefinitionId = CardDefinitionId(394);
pub const WEAKSTONE: CardDefinitionId = CardDefinitionId(395);
pub const YOTIAN_SOLDIER: CardDefinitionId = CardDefinitionId(396);
pub const AMROU_KITHKIN: CardDefinitionId = CardDefinitionId(397);
pub const CLEANSE: CardDefinitionId = CardDefinitionId(398);
pub const DAVENANT_ARCHER: CardDefinitionId = CardDefinitionId(399);
pub const DIVINE_TRANSFORMATION: CardDefinitionId = CardDefinitionId(400);
pub const GREAT_DEFENDER: CardDefinitionId = CardDefinitionId(401);
pub const KEEPERS_OF_THE_FAITH: CardDefinitionId = CardDefinitionId(402);
pub const KISMET: CardDefinitionId = CardDefinitionId(403);
pub const LIFEBLOOD: CardDefinitionId = CardDefinitionId(404);
pub const SEEKER: CardDefinitionId = CardDefinitionId(405);
pub const SHIELD_WALL: CardDefinitionId = CardDefinitionId(406);
pub const SPIRITUAL_SANCTUARY: CardDefinitionId = CardDefinitionId(407);
pub const TUNDRA_WOLVES: CardDefinitionId = CardDefinitionId(408);
pub const WALL_OF_LIGHT: CardDefinitionId = CardDefinitionId(409);
pub const ACID_RAIN: CardDefinitionId = CardDefinitionId(410);
pub const AZURE_DRAKE: CardDefinitionId = CardDefinitionId(411);
pub const BOOMERANG: CardDefinitionId = CardDefinitionId(412);
pub const FLASH_COUNTER: CardDefinitionId = CardDefinitionId(413);
pub const FLASH_FLOOD: CardDefinitionId = CardDefinitionId(414);
pub const FORCE_SPIKE: CardDefinitionId = CardDefinitionId(415);
pub const PSIONIC_ENTITY: CardDefinitionId = CardDefinitionId(416);
pub const REMOVE_SOUL: CardDefinitionId = CardDefinitionId(417);
pub const ZEPHYR_FALCON: CardDefinitionId = CardDefinitionId(418);
pub const CARRION_ANTS: CardDefinitionId = CardDefinitionId(419);
pub const CYCLOPEAN_MUMMY: CardDefinitionId = CardDefinitionId(420);
pub const FALLEN_ANGEL: CardDefinitionId = CardDefinitionId(421);
pub const GHOSTS_OF_THE_DAMNED: CardDefinitionId = CardDefinitionId(422);
pub const GREED: CardDefinitionId = CardDefinitionId(423);
pub const HEADLESS_HORSEMAN: CardDefinitionId = CardDefinitionId(424);
pub const HELL_SWARM: CardDefinitionId = CardDefinitionId(425);
pub const NETHER_VOID: CardDefinitionId = CardDefinitionId(426);
pub const ACTIVE_VOLCANO: CardDefinitionId = CardDefinitionId(427);
pub const CRIMSON_KOBOLDS: CardDefinitionId = CardDefinitionId(428);
pub const CRIMSON_MANTICORE: CardDefinitionId = CardDefinitionId(429);
pub const CROOKSHANK_KOBOLDS: CardDefinitionId = CardDefinitionId(430);
pub const ETERNAL_WARRIOR: CardDefinitionId = CardDefinitionId(431);
pub const GIANT_STRENGTH: CardDefinitionId = CardDefinitionId(432);
pub const GRAVITY_SPHERE: CardDefinitionId = CardDefinitionId(433);
pub const IMMOLATION: CardDefinitionId = CardDefinitionId(434);
pub const KOBOLD_DRILL_SERGEANT: CardDefinitionId = CardDefinitionId(435);
pub const KOBOLD_OVERLORD: CardDefinitionId = CardDefinitionId(436);
pub const KOBOLD_TASKMASTER: CardDefinitionId = CardDefinitionId(437);
pub const KOBOLDS_OF_KHER_KEEP: CardDefinitionId = CardDefinitionId(438);
pub const MOUNTAIN_YETI: CardDefinitionId = CardDefinitionId(439);
pub const PYROTECHNICS: CardDefinitionId = CardDefinitionId(440);
pub const RAGING_BULL: CardDefinitionId = CardDefinitionId(441);
pub const SPINAL_VILLAIN: CardDefinitionId = CardDefinitionId(442);
pub const WALL_OF_EARTH: CardDefinitionId = CardDefinitionId(443);
pub const WALL_OF_HEAT: CardDefinitionId = CardDefinitionId(444);
pub const WALL_OF_OPPOSITION: CardDefinitionId = CardDefinitionId(445);
pub const BARBARY_APES: CardDefinitionId = CardDefinitionId(446);
pub const CAT_WARRIORS: CardDefinitionId = CardDefinitionId(447);
pub const CONCORDANT_CROSSROADS: CardDefinitionId = CardDefinitionId(448);
pub const DURKWOOD_BOARS: CardDefinitionId = CardDefinitionId(449);
pub const ELVEN_RIDERS: CardDefinitionId = CardDefinitionId(450);
pub const EMERALD_DRAGONFLY: CardDefinitionId = CardDefinitionId(451);
pub const HORNET_COBRA: CardDefinitionId = CardDefinitionId(452);
pub const KILLER_BEES: CardDefinitionId = CardDefinitionId(453);
pub const MOSS_MONSTER: CardDefinitionId = CardDefinitionId(454);
pub const PIXIE_QUEEN: CardDefinitionId = CardDefinitionId(455);
pub const PRADESH_GYPSIES: CardDefinitionId = CardDefinitionId(456);
pub const RADJAN_SPIRIT: CardDefinitionId = CardDefinitionId(457);
pub const UNTAMED_WILDS: CardDefinitionId = CardDefinitionId(458);
pub const FARMSTEAD: CardDefinitionId = CardDefinitionId(459);
pub const BURROWING: CardDefinitionId = CardDefinitionId(460);
pub const DWARVEN_DEMOLITION_TEAM: CardDefinitionId = CardDefinitionId(461);
pub const DWARVEN_WARRIORS: CardDefinitionId = CardDefinitionId(462);
pub const EARTH_ELEMENTAL: CardDefinitionId = CardDefinitionId(463);
pub const FIRE_ELEMENTAL: CardDefinitionId = CardDefinitionId(464);
pub const FIREBREATHING: CardDefinitionId = CardDefinitionId(465);
pub const FLASHFIRES: CardDefinitionId = CardDefinitionId(466);
pub const GRAY_OGRE: CardDefinitionId = CardDefinitionId(467);
pub const HILL_GIANT: CardDefinitionId = CardDefinitionId(468);
pub const HURLOON_MINOTAUR: CardDefinitionId = CardDefinitionId(469);
pub const MANABARBS: CardDefinitionId = CardDefinitionId(470);
pub const MONSS_GOBLIN_RAIDERS: CardDefinitionId = CardDefinitionId(471);
pub const ORCISH_ARTILLERY: CardDefinitionId = CardDefinitionId(472);
pub const ORCISH_ORIFLAMME: CardDefinitionId = CardDefinitionId(473);
pub const ROC_OF_KHER_RIDGES: CardDefinitionId = CardDefinitionId(474);
pub const SHIVAN_DRAGON: CardDefinitionId = CardDefinitionId(475);
pub const TUNNEL: CardDefinitionId = CardDefinitionId(476);
pub const WALL_OF_FIRE: CardDefinitionId = CardDefinitionId(477);
pub const CRAW_WURM: CardDefinitionId = CardDefinitionId(478);
pub const ELVISH_ARCHERS: CardDefinitionId = CardDefinitionId(479);
pub const FORCE_OF_NATURE: CardDefinitionId = CardDefinitionId(480);
pub const FUNGUSAUR: CardDefinitionId = CardDefinitionId(481);
pub const GIANT_SPIDER: CardDefinitionId = CardDefinitionId(482);
pub const GRIZZLY_BEARS: CardDefinitionId = CardDefinitionId(483);
pub const HURRICANE: CardDefinitionId = CardDefinitionId(484);
pub const ICE_STORM: CardDefinitionId = CardDefinitionId(485);
pub const IRONROOT_TREEFOLK: CardDefinitionId = CardDefinitionId(486);
pub const LEY_DRUID: CardDefinitionId = CardDefinitionId(487);
pub const LIFEFORCE: CardDefinitionId = CardDefinitionId(488);
pub const SHANODIN_DRYADS: CardDefinitionId = CardDefinitionId(489);
pub const STREAM_OF_LIFE: CardDefinitionId = CardDefinitionId(490);
pub const TRANQUILITY: CardDefinitionId = CardDefinitionId(491);
pub const TSUNAMI: CardDefinitionId = CardDefinitionId(492);
pub const VERDURAN_ENCHANTRESS: CardDefinitionId = CardDefinitionId(493);
pub const WALL_OF_ICE: CardDefinitionId = CardDefinitionId(494);
pub const WALL_OF_WOOD: CardDefinitionId = CardDefinitionId(495);
pub const WAR_MAMMOTH: CardDefinitionId = CardDefinitionId(496);
pub const WEB: CardDefinitionId = CardDefinitionId(497);
pub const BASALT_MONOLITH: CardDefinitionId = CardDefinitionId(498);
pub const CELESTIAL_PRISM: CardDefinitionId = CardDefinitionId(499);
pub const CRYSTAL_ROD: CardDefinitionId = CardDefinitionId(500);
pub const DINGUS_EGG: CardDefinitionId = CardDefinitionId(501);
pub const IVORY_CUP: CardDefinitionId = CardDefinitionId(502);
pub const OBSIANUS_GOLEM: CardDefinitionId = CardDefinitionId(503);
pub const ROD_OF_RUIN: CardDefinitionId = CardDefinitionId(504);
pub const SOUL_NET: CardDefinitionId = CardDefinitionId(505);
pub const THRONE_OF_BONE: CardDefinitionId = CardDefinitionId(506);
pub const WOODEN_SPHERE: CardDefinitionId = CardDefinitionId(507);
pub const ADUN_OAKENSHIELD: CardDefinitionId = CardDefinitionId(508);
pub const AXELROD_GUNNARSON: CardDefinitionId = CardDefinitionId(509);
pub const BARKTOOTH_WARBEARD: CardDefinitionId = CardDefinitionId(510);
pub const JACQUES_LE_VERT: CardDefinitionId = CardDefinitionId(511);
pub const JASMINE_BOREAL: CardDefinitionId = CardDefinitionId(512);
pub const JEDIT_OJANEN: CardDefinitionId = CardDefinitionId(513);
pub const JERRARD_OF_THE_CLOSED_FIST: CardDefinitionId = CardDefinitionId(514);
pub const KASIMIR_THE_LONE_WOLF: CardDefinitionId = CardDefinitionId(515);
pub const LADY_CALERIA: CardDefinitionId = CardDefinitionId(516);
pub const LADY_ORCA: CardDefinitionId = CardDefinitionId(517);
pub const NICOL_BOLAS: CardDefinitionId = CardDefinitionId(518);
pub const PALLADIA_MORS: CardDefinitionId = CardDefinitionId(519);
pub const PAVEL_MALIKI: CardDefinitionId = CardDefinitionId(520);
pub const PRINCESS_LUCREZIA: CardDefinitionId = CardDefinitionId(521);
pub const RAMIREZ_DEPIETRO: CardDefinitionId = CardDefinitionId(522);
pub const RIVEN_TURNBULL: CardDefinitionId = CardDefinitionId(523);
pub const SIR_SHANDLAR_OF_EBERYN: CardDefinitionId = CardDefinitionId(524);
pub const SIVITRI_SCARZAM: CardDefinitionId = CardDefinitionId(525);
pub const SUNASTIAN_FALCONER: CardDefinitionId = CardDefinitionId(526);
pub const THE_LADY_OF_THE_MOUNTAIN: CardDefinitionId = CardDefinitionId(527);
pub const TOBIAS_ANDRION: CardDefinitionId = CardDefinitionId(528);
pub const TOR_WAUKI: CardDefinitionId = CardDefinitionId(529);
pub const TORSTEN_VON_URSUS: CardDefinitionId = CardDefinitionId(530);
pub const TUKNIR_DEATHLOCK: CardDefinitionId = CardDefinitionId(531);
pub const VAEVICTIS_ASMADI: CardDefinitionId = CardDefinitionId(532);
pub const XIRA_ARIEN: CardDefinitionId = CardDefinitionId(533);
pub const ARENA_OF_THE_ANCIENTS: CardDefinitionId = CardDefinitionId(534);
pub const KARAKAS: CardDefinitionId = CardDefinitionId(535);
pub const THE_TABERNACLE_AT_PENDRELL_VALE: CardDefinitionId = CardDefinitionId(536);
pub const TYPHOON: CardDefinitionId = CardDefinitionId(537);
pub const BIRD_TOKEN_4_4_RED: CardDefinitionId = CardDefinitionId(538);
pub const CITIZEN_TOKEN_1_1_WHITE: CardDefinitionId = CardDefinitionId(539);
pub const THRULL_TOKEN_0_1_BLACK: CardDefinitionId = CardDefinitionId(540);
pub const EXORCIST: CardDefinitionId = CardDefinitionId(541);
pub const HOLY_LIGHT: CardDefinitionId = CardDefinitionId(542);
pub const MORALE: CardDefinitionId = CardDefinitionId(543);
pub const SQUIRE: CardDefinitionId = CardDefinitionId(544);
pub const TIVADARS_CRUSADE: CardDefinitionId = CardDefinitionId(545);
pub const WITCH_HUNTER: CardDefinitionId = CardDefinitionId(546);
pub const ELECTRIC_EEL: CardDefinitionId = CardDefinitionId(547);
pub const FLOOD: CardDefinitionId = CardDefinitionId(548);
pub const RIPTIDE: CardDefinitionId = CardDefinitionId(549);
pub const SUNKEN_CITY: CardDefinitionId = CardDefinitionId(550);
pub const ASHES_TO_ASHES: CardDefinitionId = CardDefinitionId(551);
pub const BOG_IMP: CardDefinitionId = CardDefinitionId(552);
pub const BOG_RATS: CardDefinitionId = CardDefinitionId(553);
pub const RUKH_EGG: CardDefinitionId = CardDefinitionId(554);
pub const GRAVE_ROBBERS: CardDefinitionId = CardDefinitionId(555);
pub const MARSH_GAS: CardDefinitionId = CardDefinitionId(556);
pub const UNCLE_ISTVAN: CardDefinitionId = CardDefinitionId(557);
pub const BROTHERS_OF_FIRE: CardDefinitionId = CardDefinitionId(558);
pub const CAVE_PEOPLE: CardDefinitionId = CardDefinitionId(559);
pub const FISSURE: CardDefinitionId = CardDefinitionId(560);
pub const GOBLIN_HERO: CardDefinitionId = CardDefinitionId(561);
pub const INFERNO: CardDefinitionId = CardDefinitionId(562);
pub const SISTERS_OF_THE_FLAME: CardDefinitionId = CardDefinitionId(563);
pub const CARNIVOROUS_PLANT: CardDefinitionId = CardDefinitionId(564);
pub const HIDDEN_PATH: CardDefinitionId = CardDefinitionId(565);
pub const LAND_LEECHES: CardDefinitionId = CardDefinitionId(566);
pub const SCAVENGER_FOLK: CardDefinitionId = CardDefinitionId(567);
pub const TRACKER: CardDefinitionId = CardDefinitionId(568);
pub const SCARWOOD_GOBLINS: CardDefinitionId = CardDefinitionId(569);
pub const DARK_HEART_OF_THE_WOOD: CardDefinitionId = CardDefinitionId(570);
pub const BONE_FLUTE: CardDefinitionId = CardDefinitionId(571);
pub const BOOK_OF_RASS: CardDefinitionId = CardDefinitionId(572);
pub const FOUNTAIN_OF_YOUTH: CardDefinitionId = CardDefinitionId(573);
pub const SKULL_OF_ORM: CardDefinitionId = CardDefinitionId(574);
pub const WATER_WURM: CardDefinitionId = CardDefinitionId(575);
pub const TOWER_OF_COIREALL: CardDefinitionId = CardDefinitionId(576);
pub const SAFE_HAVEN: CardDefinitionId = CardDefinitionId(577);
pub const SCARWOOD_HAG: CardDefinitionId = CardDefinitionId(578);
pub const ICATIAN_LIEUTENANT: CardDefinitionId = CardDefinitionId(579);
pub const ICATIAN_PRIEST: CardDefinitionId = CardDefinitionId(580);
pub const ICATIAN_SCOUT: CardDefinitionId = CardDefinitionId(581);
pub const ICATIAN_TOWN: CardDefinitionId = CardDefinitionId(582);
pub const HOMARID_SHAMAN: CardDefinitionId = CardDefinitionId(583);
pub const RIVER_MERFOLK: CardDefinitionId = CardDefinitionId(584);
pub const VODALIAN_MAGE: CardDefinitionId = CardDefinitionId(585);
pub const VODALIAN_SOLDIERS: CardDefinitionId = CardDefinitionId(586);
pub const BASAL_THRULL: CardDefinitionId = CardDefinitionId(587);
pub const BREEDING_PIT: CardDefinitionId = CardDefinitionId(588);
pub const SORCERESS_QUEEN: CardDefinitionId = CardDefinitionId(589);
pub const ORC_GENERAL: CardDefinitionId = CardDefinitionId(590);
pub const DWARVEN_LIEUTENANT: CardDefinitionId = CardDefinitionId(591);
pub const ELVEN_FORTRESS: CardDefinitionId = CardDefinitionId(592);
pub const AEOLIPILE: CardDefinitionId = CardDefinitionId(593);
pub const ELVEN_LYRE: CardDefinitionId = CardDefinitionId(594);
pub const RING_OF_RENEWAL: CardDefinitionId = CardDefinitionId(595);
pub const DWARVEN_RUINS: CardDefinitionId = CardDefinitionId(596);
pub const EBON_STRONGHOLD: CardDefinitionId = CardDefinitionId(597);
pub const HAVENWOOD_BATTLEGROUND: CardDefinitionId = CardDefinitionId(598);
pub const RUINS_OF_TROKAIR: CardDefinitionId = CardDefinitionId(599);
pub const SVYELUNITE_TEMPLE: CardDefinitionId = CardDefinitionId(600);
pub const THELONITE_DRUID: CardDefinitionId = CardDefinitionId(601);
pub const WASP_TOKEN_1_1_COLORLESS: CardDefinitionId = CardDefinitionId(602);
pub const MINOR_DEMON_TOKEN_1_1_BLACK_RED: CardDefinitionId = CardDefinitionId(603);
pub const THE_HIVE: CardDefinitionId = CardDefinitionId(604);
pub const BORIS_DEVILBOON: CardDefinitionId = CardDefinitionId(605);
pub const GUARDIAN_BEAST: CardDefinitionId = CardDefinitionId(606);
pub const RING_OF_MARUF: CardDefinitionId = CardDefinitionId(1362);
pub const BLOODSTAINED_MIRE: CardDefinitionId = CardDefinitionId(1363);
pub const POLLUTED_DELTA: CardDefinitionId = CardDefinitionId(1364);
pub const WINDSWEPT_HEATH: CardDefinitionId = CardDefinitionId(1365);
pub const UGINS_NEXUS: CardDefinitionId = CardDefinitionId(1368);
