//! Duel Commander committee rules and named bans, consulted 2026-09-12.
//! Rules: https://www.duelcommander.org/rules/duelcommander_comprehensiverules/
//! Ban policy (2026-07-27): https://www.duelcommander.org/banlist/
//! Construction and category-wide card legality remain deferred.
use super::{CommanderFormatDefinition, FormatRules};

pub(super) const DEFINITION: CommanderFormatDefinition = CommanderFormatDefinition {
    rules: FormatRules {
        starting_life: 20,
        ..super::commander::RULES
    },
    total_deck_size: 100,
    commander_damage_limit: None,
    one_command_zone_commander: true,
    commander_swapping: true,
    outside_game_effects: false,
    banned_cards: BANNED_CARDS,
    commander_only_banned_cards: COMMANDER_ONLY_BANNED_CARDS,
    companion_only_banned_cards: &["Lutri, the Spellchaser"],
};

const BANNED_CARDS: &[&str] = &[
    "Ancestral Recall",
    "Ancient Tomb",
    "Back to Basics",
    "Balance",
    "Bazaar of Baghdad",
    "Black Lotus",
    "Blood Moon",
    "Capture of Jingzhou",
    "Cavern of Souls",
    "Channel",
    "Chrome Mox",
    "Comet, Stellar Pup",
    "Dark Ritual",
    "Deadly Rollick",
    "Deflecting Swat",
    "Dig Through Time",
    "Emrakul, the Aeons Torn",
    "Entomb",
    "Fastbond",
    "Field of the Dead",
    "Fierce Guardianship",
    "Flawless Maneuver",
    "Food Chain",
    "Force of Will",
    "Gaea's Cradle",
    "Genesis Storm",
    "Gifts Ungiven",
    "Grim Monolith",
    "Hermit Druid",
    "Humility",
    "Imperial Seal",
    "Invert Polarity",
    "Jeweled Lotus",
    "Karakas",
    "Library of Alexandria",
    "Lion's Eye Diamond",
    "Lotus Petal",
    "Maddening Hex",
    "Mana Crypt",
    "Mana Drain",
    "Mana Vault",
    "Mishra's Workshop",
    "Mox Amber",
    "Mox Diamond",
    "Mox Emerald",
    "Mox Jet",
    "Mox Opal",
    "Mox Pearl",
    "Mox Ruby",
    "Mox Sapphire",
    "Mystical Tutor",
    "Nadu, Winged Wisdom",
    "Natural Order",
    "Oath of Druids",
    "Price of Progress",
    "Protean Hulk",
    "Ragavan, Nimble Pilferer",
    "Rain of Filth",
    "Reanimate",
    "Scapeshift",
    "Sensei's Divining Top",
    "Serra's Sanctum",
    "Sol Ring",
    "Strip Mine",
    "Temporal Manipulation",
    "Thassa's Oracle",
    "The One Ring",
    "The Tabernacle at Pendrell Vale",
    "Time Vault",
    "Time Walk",
    "Time Warp",
    "Timetwister",
    "Tinker",
    "Tolarian Academy",
    "Treasure Cruise",
    "Underworld Breach",
    "Uro, Titan of Nature's Wrath",
    "Vampiric Tutor",
    "Wasteland",
    "White Plume Adventurer",
    "Cleanse",
    "Crusade",
    "Imprison",
    "Invoke Prejudice",
    "Jihad",
    "Pradesh Gypsies",
    "Stone-Throwing Devils",
    "Chaos Orb",
    "Falling Star",
    "Shahrazad",
];

const COMMANDER_ONLY_BANNED_CARDS: &[&str] = &[
    "Ajani, Nacatl Pariah // Ajani, Nacatl Avenger",
    "Arahbo, Roar of the World",
    "Derevi, Empyrial Tactician",
    "Dihada, Binder of Wills",
    "Edgar Markov",
    "Edric, Spymaster of Trest",
    "Eris, Roar of the Storm",
    "Ezio Auditore da Firenze",
    "Geist of Saint Traft",
    "Hogaak, Arisen Necropolis",
    "Inalla, Archmage Ritualist",
    "Krark, the Thumbless",
    "Lumra, Bellow of the Woods",
    "Minsc & Boo, Timeless Heroes",
    "Old Stickfingers",
    "Oloro, Ageless Ascetic",
    "Omnath, Locus of Creation",
    "Prime Speaker Vannifar",
    "Raffine, Scheming Seer",
    "Rograkh, Son of Rohgahh",
    "Shorikai, Genesis Engine",
    "Spider-Man 2099",
    "Tamiyo, Inquisitive Student",
    "The Fantasticar",
    "Urza, Lord High Artificer",
    "Vial Smasher the Fierce",
    "Yuriko, the Tiger's Shadow",
];
