//! Cataloged subset of the eternal card pool, with policy checked 2026-09-12.
//!
//! Source: https://magic.wizards.com/en/banned-restricted-list
//! Named category bans (ante, Conspiracy, offensive cards, stickers and
//! Attractions) are expanded using the local Scryfall snapshot. Missing sets
//! and cards need not be cataloged to register either format.

use super::{CONSTRUCTED_RULES, SetFormatDefinition};
use crate::card::{CardSet, sets};

// Only the tournament-eligible paper sets represented in this catalog. Add
// future eligible sets here; a new novelty or digital set is not legal by default.
const ALLOWED_SETS: &[CardSet] = &[
    sets::outlaws_of_thunder_junction_commander::SET,
    sets::warhammer_40_000_commander::SET,
    sets::assassin_s_creed::SET,
    sets::alpha::SET,
    sets::beta::SET,
    sets::unlimited::SET,
    sets::arabian_nights::SET,
    sets::antiquities::SET,
    sets::revised::SET,
    sets::legends::SET,
    sets::the_dark::SET,
    sets::fallen_empires::SET,
    sets::harper_prism_book_promos::SET,
    sets::dragon_con::SET,
    sets::fourth_edition::SET,
    sets::ice_age::SET,
    sets::chronicles::SET,
    sets::alliances::SET,
    sets::mirage::SET,
    sets::portal::SET,
    sets::visions::SET,
    sets::weatherlight::SET,
    sets::tempest::SET,
    sets::stronghold::SET,
    sets::portal_second_age::SET,
    sets::urzas_saga::SET,
    sets::urzas_legacy::SET,
    sets::urzas_destiny::SET,
    sets::mercadian_masques::SET,
    sets::starter_1999::SET,
    sets::nemesis::SET,
    sets::invasion::SET,
    sets::planeshift::SET,
    sets::seventh_edition::SET,
    sets::apocalypse::SET,
    sets::odyssey::SET,
    sets::torment::SET,
    sets::judgment::SET,
    sets::onslaught::SET,
    sets::legions::SET,
    sets::scourge::SET,
    sets::mirrodin::SET,
    sets::darksteel::SET,
    sets::fifth_dawn::SET,
    sets::champions_of_kamigawa::SET,
    sets::betrayers_of_kamigawa::SET,
    sets::planar_chaos::SET,
    sets::future_sight::SET,
    sets::lorwyn::SET,
    sets::morningtide::SET,
    sets::mirrodin_besieged::SET,
    sets::new_phyrexia::SET,
    sets::conflux::SET,
    sets::zendikar::SET,
    sets::shadowmoor::SET,
    sets::eventide::SET,
    sets::shards_of_alara::SET,
    sets::worldwake::SET,
    sets::scars_of_mirrodin::SET,
    sets::magic_2010::SET,
    sets::magic_2011::SET,
    sets::archenemy::SET,
    sets::rise_of_the_eldrazi::SET,
    sets::magic_2012::SET,
    sets::commander_2011::SET,
    sets::innistrad::SET,
    sets::dark_ascension::SET,
    sets::avacyn_restored::SET,
    sets::magic_2013::SET,
    sets::return_to_ravnica::SET,
    sets::gatecrash::SET,
    sets::dragons_maze::SET,
    sets::magic_2014::SET,
    sets::theros::SET,
    sets::planechase_2012::SET,
    sets::commander_2013::SET,
    sets::journey_into_nyx::SET,
    sets::conspiracy::SET,
    sets::magic_2015::SET,
    sets::commander_2014::SET,
    sets::khans_of_tarkir::SET,
    sets::dragons_of_tarkir::SET,
    sets::commander_2015::SET,
    sets::ixalan::SET,
    sets::battlebond::SET,
    sets::magic_2020::SET,
    sets::modern_horizons::SET,
    sets::war_of_the_spark::SET,
    sets::throne_of_eldraine::SET,
    sets::theros_beyond_death::SET,
    sets::zendikar_rising::SET,
    sets::ikoria::SET,
    sets::kaldheim::SET,
    sets::commander_2021::SET,
    sets::strixhaven_school_of_mages::SET,
    sets::modern_horizons_2::SET,
    sets::adventures_in_the_forgotten_realms::SET,
    sets::innistrad_midnight_hunt::SET,
    sets::innistrad_crimson_vow::SET,
    sets::innistrad_crimson_vow_commander::SET,
    sets::kamigawa_neon_dynasty::SET,
    sets::kamigawa_neon_dynasty_commander::SET,
    sets::streets_of_new_capenna::SET,
    sets::streets_of_new_capenna_commander::SET,
    sets::commander_legends_baldurs_gate::SET,
    sets::dominaria_united::SET,
    sets::the_brothers_war::SET,
    sets::eternal_masters::SET,
    sets::eldritch_moon::SET,
    sets::conspiracy_take_the_crown::SET,
    sets::kaladesh::SET,
    sets::aether_revolt::SET,
    sets::amonkhet::SET,
    sets::phyrexia_all_will_be_one::SET,
    sets::phyrexia_all_will_be_one_commander::SET,
    sets::march_of_the_machine::SET,
    sets::lord_of_the_rings::SET,
    sets::lord_of_the_rings_commander::SET,
    sets::wilds_of_eldraine::SET,
    sets::murders_at_karlov_manor::SET,
    sets::ravnica_clue_edition::SET,
    sets::fallout::SET,
    sets::lost_caverns_of_ixalan::SET,
    sets::modern_horizons_3::SET,
    sets::outlaws_of_thunder_junction::SET,
    sets::the_big_score::SET,
    sets::modern_horizons_3_commander::SET,
    sets::bloomburrow::SET,
    sets::bloomburrow_commander::SET,
    sets::duskmourn_house_of_horror::SET,
    sets::duskmourn_house_of_horror_commander::SET,
    sets::foundations_jumpstart::SET,
    sets::tarkir_dragonstorm::SET,
    sets::aetherdrift::SET,
    sets::final_fantasy::SET,
    sets::final_fantasy_commander::SET,
    sets::through_the_omenpaths::SET,
    sets::homelands::SET,
    sets::fifth_edition::SET,
    sets::exodus::SET,
    sets::classic_sixth_edition::SET,
    sets::prophecy::SET,
    sets::saviors_of_kamigawa::SET,
    sets::ravnica_city_of_guilds::SET,
    sets::guildpact::SET,
    sets::dissension::SET,
    sets::time_spiral::SET,
    sets::alara_reborn::SET,
    sets::fate_reforged::SET,
    sets::battle_for_zendikar::SET,
    sets::magic_origins::SET,
    sets::shadows_over_innistrad::SET,
    sets::oath_of_the_gatewatch::SET,
    sets::hour_of_devastation::SET,
    sets::core_set_2019::SET,
    sets::rivals_of_ixalan::SET,
    sets::commander_2018::SET,
    sets::ravnica_allegiance::SET,
    sets::commander_2020::SET,
    sets::core_set_2021::SET,
    sets::magic_foundations::SET,
    sets::marvels_spider_man::SET,
    sets::avatar_the_last_airbender::SET,
    sets::edge_of_eternities::SET,
    sets::edge_of_eternities_commander::SET,
    sets::lorwyn_eclipsed::SET,
    sets::secrets_of_strixhaven::SET,
    sets::teenage_mutant_ninja_turtles::SET,
    sets::marvel_super_heroes::SET,
    sets::portal_three_kingdoms::SET,
    sets::coldsnap::SET,
    sets::born_of_the_gods::SET,
    sets::commander_2017::SET,
    sets::dominaria::SET,
    sets::commander_legends::SET,
    sets::dominaria_united_commander::SET,
    sets::march_of_the_machine_commander::SET,
    sets::lost_caverns_of_ixalan_commander::SET,
    sets::guilds_of_ravnica::SET,
    sets::commander_masters::SET,
    sets::doctor_who::SET,
    sets::marvel_super_heroes_commander::SET,
    sets::global_series_jiang_yanggu_and_mu_yanling::SET,
    sets::jumpstart::SET,
    sets::kaldheim_commander::SET,
    sets::jumpstart_2022::SET,
    sets::avatar_the_last_airbender_eternal::SET,
    sets::the_hobbit::SET,
];

const SHARED_BANS: &[&str] = &[
    "\"Lifetime\" Pass Holder",
    "\"Name Sticker\" Goblin",
    "Adriana's Valor",
    "Advantageous Proclamation",
    "Aerialephant",
    "Ambassador Blorpityblorpboop",
    "Amulet of Quoz",
    "Assemble the Rank and Vile",
    "Baaallerina",
    "Backup Plan",
    "Bioluminary",
    "Brago's Favor",
    "Bronze Tablet",
    "Carnival Carnivore",
    "Chaos Orb",
    "Chicken Troupe",
    "Clandestine Chameleon",
    "Cleanse",
    "Coming Attraction",
    "Command Performance",
    "Complaints Clerk",
    "Contract from Below",
    "Crusade",
    "Darkpact",
    "Deadbeat Attendant",
    "Dee Kay, Finder of the Lost",
    "Demonic Attorney",
    "Discourtesy Clerk",
    "Done for the Day",
    "Double Stroke",
    "Draconian Gate-Bot",
    "Echoing Boon",
    "Emissary's Ploy",
    "Falling Star",
    "Fight the _____ Fight",
    "Finishing Move",
    "Glitterflitter",
    "Hired Heist",
    "Hold the Perimeter",
    "Hymn of the Wilds",
    "Immediate Action",
    "Imprison",
    "Incendiary Dissent",
    "Invoke Prejudice",
    "Iterative Analysis",
    "Jeweled Bird",
    "Jihad",
    "Last Voyage of the _____",
    "Line Cutter",
    "Lineprancers",
    "Make a _____ Splash",
    "Minotaur de Force",
    "Monitor Monitor",
    "Muzzio's Preparations",
    "Myra the Magnificent",
    "Natural Unity",
    "Park Bleater",
    "Petting Zookeeper",
    "Pin Collection",
    "Power Play",
    "Pradesh Gypsies",
    "Prize Wall",
    "Proficient Pyrodancer",
    "Quick Fixer",
    "Rad Rascal",
    "Rebirth",
    "Ride Guide",
    "Robo-Piñata",
    "Roxi, Publicist to the Stars",
    "Scampire",
    "Seasoned Buttoneer",
    "Secret Summoning",
    "Secrets of Paradise",
    "Sentinel Dispatch",
    "Shahrazad",
    "Soul Swindler",
    "Sovereign's Realm",
    "Spinnerette, Arachnobat",
    "Squirrel Squatters",
    "Step Right Up",
    "Stiltstrider",
    "Stone-Throwing Devils",
    "Summoner's Bond",
    "Sword-Swallowing Seraph",
    "Tempest Efreet",
    "The Most Dangerous Gamer",
    "Ticketomaton",
    "Timmerian Fiends",
    "Tusk and Whiskers",
    "Unexpected Potential",
    "Weight Advantage",
    "Wicker Picker",
    "Wizards of the _____",
    "Wolf in _____ Clothing",
    "Worldknit",
    "_____ Balls of Fire",
    "_____ Bird Gets the Worm",
    "_____ Goblin",
    "_____ _____ Rocketship",
    "_____ _____ _____ Trespasser",
    "_____-o-saurus",
];

const LEGACY_BANS: &[&str] = &[
    "\"Lifetime\" Pass Holder",
    "\"Name Sticker\" Goblin",
    "Adriana's Valor",
    "Advantageous Proclamation",
    "Aerialephant",
    "Ambassador Blorpityblorpboop",
    "Amulet of Quoz",
    "Ancestral Recall",
    "Arcum's Astrolabe",
    "Assemble the Rank and Vile",
    "Baaallerina",
    "Backup Plan",
    "Balance",
    "Bazaar of Baghdad",
    "Bioluminary",
    "Black Lotus",
    "Brago's Favor",
    "Bronze Tablet",
    "Candelabra of Tawnos",
    "Carnival Carnivore",
    "Channel",
    "Chaos Orb",
    "Chicken Troupe",
    "Clandestine Chameleon",
    "Cleanse",
    "Coming Attraction",
    "Command Performance",
    "Complaints Clerk",
    "Contract from Below",
    "Crusade",
    "Darkpact",
    "Deadbeat Attendant",
    "Deathrite Shaman",
    "Dee Kay, Finder of the Lost",
    "Demonic Attorney",
    "Demonic Consultation",
    "Demonic Tutor",
    "Dig Through Time",
    "Discourtesy Clerk",
    "Done for the Day",
    "Double Stroke",
    "Draconian Gate-Bot",
    "Dreadhorde Arcanist",
    "Earthcraft",
    "Echoing Boon",
    "Emissary's Ploy",
    "Entomb",
    "Expressive Iteration",
    "Falling Star",
    "Fastbond",
    "Fight the _____ Fight",
    "Finishing Move",
    "Flash",
    "Frantic Search",
    "Gitaxian Probe",
    "Glitterflitter",
    "Goblin Recruiter",
    "Grief",
    "Gush",
    "Hermit Druid",
    "Hired Heist",
    "Hold the Perimeter",
    "Hymn of the Wilds",
    "Immediate Action",
    "Imperial Seal",
    "Imprison",
    "Incendiary Dissent",
    "Invoke Prejudice",
    "Iterative Analysis",
    "Jeweled Bird",
    "Jihad",
    "Last Voyage of the _____",
    "Library of Alexandria",
    "Line Cutter",
    "Lineprancers",
    "Lurrus of the Dream-Den",
    "Make a _____ Splash",
    "Mana Crypt",
    "Mana Drain",
    "Mana Vault",
    "Memory Jar",
    "Mental Misstep",
    "Mind Twist",
    "Minotaur de Force",
    "Mishra's Workshop",
    "Monitor Monitor",
    "Mox Emerald",
    "Mox Jet",
    "Mox Pearl",
    "Mox Ruby",
    "Mox Sapphire",
    "Muzzio's Preparations",
    "Myra the Magnificent",
    "Mystical Tutor",
    "Nadu, Winged Wisdom",
    "Natural Unity",
    "Necropotence",
    "Oath of Druids",
    "Oko, Thief of Crowns",
    "Park Bleater",
    "Petting Zookeeper",
    "Pin Collection",
    "Power Play",
    "Pradesh Gypsies",
    "Prize Wall",
    "Proficient Pyrodancer",
    "Psychic Frog",
    "Quick Fixer",
    "Rad Rascal",
    "Ragavan, Nimble Pilferer",
    "Rebirth",
    "Ride Guide",
    "Robo-Piñata",
    "Roxi, Publicist to the Stars",
    "Scampire",
    "Seasoned Buttoneer",
    "Secret Summoning",
    "Secrets of Paradise",
    "Sensei's Divining Top",
    "Sentinel Dispatch",
    "Shahrazad",
    "Skullclamp",
    "Sol Ring",
    "Soul Swindler",
    "Sovereign's Realm",
    "Sowing Mycospawn",
    "Spinnerette, Arachnobat",
    "Squirrel Squatters",
    "Step Right Up",
    "Stiltstrider",
    "Stone-Throwing Devils",
    "Strip Mine",
    "Summoner's Bond",
    "Survival of the Fittest",
    "Sword-Swallowing Seraph",
    "Tempest Efreet",
    "The Fantasticar",
    "The Most Dangerous Gamer",
    "Ticketomaton",
    "Time Vault",
    "Time Walk",
    "Timetwister",
    "Timmerian Fiends",
    "Tinker",
    "Tolarian Academy",
    "Treasure Cruise",
    "Troll of Khazad-dûm",
    "Tusk and Whiskers",
    "Undercity Informer",
    "Underworld Breach",
    "Unexpected Potential",
    "Vampiric Tutor",
    "Vexing Bauble",
    "Weight Advantage",
    "Wheel of Fortune",
    "White Plume Adventurer",
    "Wicker Picker",
    "Windfall",
    "Wizards of the _____",
    "Wolf in _____ Clothing",
    "Worldknit",
    "Wrenn and Six",
    "Yawgmoth's Bargain",
    "Yawgmoth's Will",
    "Zirda, the Dawnwaker",
    "_____ Balls of Fire",
    "_____ Bird Gets the Worm",
    "_____ Goblin",
    "_____ _____ Rocketship",
    "_____ _____ _____ Trespasser",
    "_____-o-saurus",
];

const VINTAGE_RESTRICTED: &[&str] = &[
    "Ancestral Recall",
    "Balance",
    "Black Lotus",
    "Brainstorm",
    "Chalice of the Void",
    "Channel",
    "Demonic Consultation",
    "Demonic Tutor",
    "Dig Through Time",
    "Flash",
    "Gitaxian Probe",
    "Golgari Grave-Troll",
    "Gush",
    "Imperial Seal",
    "Karn, the Great Creator",
    "Library of Alexandria",
    "Lion's Eye Diamond",
    "Lodestone Golem",
    "Lotus Petal",
    "Mana Crypt",
    "Mana Vault",
    "Memory Jar",
    "Mental Misstep",
    "Merchant Scroll",
    "Mind's Desire",
    "Monastery Mentor",
    "Mox Emerald",
    "Mox Jet",
    "Mox Pearl",
    "Mox Ruby",
    "Mox Sapphire",
    "Mystic Forge",
    "Mystical Tutor",
    "Narset, Parter of Veils",
    "Necropotence",
    "Sol Ring",
    "Strip Mine",
    "The Fantasticar",
    "Thorn of Amethyst",
    "Time Vault",
    "Time Walk",
    "Timetwister",
    "Tinker",
    "Tolarian Academy",
    "Treasure Cruise",
    "Trinisphere",
    "Urza's Saga",
    "Vampiric Tutor",
    "Vexing Bauble",
    "Wheel of Fortune",
    "Windfall",
    "Yawgmoth's Will",
];

pub(super) const LEGACY: SetFormatDefinition = SetFormatDefinition {
    rules: CONSTRUCTED_RULES,
    allowed_sets: ALLOWED_SETS,
    additional_allowed_cards: &[],
    banned_cards: LEGACY_BANS,
    restricted_cards: &[],
};

pub(super) const VINTAGE: SetFormatDefinition = SetFormatDefinition {
    rules: CONSTRUCTED_RULES,
    allowed_sets: ALLOWED_SETS,
    additional_allowed_cards: &[],
    banned_cards: SHARED_BANS,
    restricted_cards: VINTAGE_RESTRICTED,
};
