//! Exhaustive diagnostic names, with no declaration payloads or card identities.

#[allow(clippy::too_many_lines)]
pub(crate) const fn effect_kind(value: crate::EffectDef) -> &'static str {
    match value {
        crate::EffectDef::Perform(..) => "Perform",
        crate::EffectDef::WithCosts { .. } => "WithCosts",
        crate::EffectDef::AddCounters { .. } => "AddCounters",
        crate::EffectDef::ChooseCounterKind { .. } => "ChooseCounterKind",
        crate::EffectDef::ModifyCounters { .. } => "ModifyCounters",
        crate::EffectDef::ChooseEffect { .. } => "ChooseEffect",
        crate::EffectDef::AddMana(..) => "AddMana",
        crate::EffectDef::AddManaEqualTo { .. } => "AddManaEqualTo",
        crate::EffectDef::GainClassLevel { .. } => "GainClassLevel",
        crate::EffectDef::AddPlayerCounters { .. } => "AddPlayerCounters",
        crate::EffectDef::Apply { .. } => "Apply",
        crate::EffectDef::WithRule { .. } => "WithRule",
        crate::EffectDef::Attach { .. } => "Attach",
        crate::EffectDef::AttachToSource { .. } => "AttachToSource",
        crate::EffectDef::PairWithSource { .. } => "PairWithSource",
        crate::EffectDef::Reconfigure { .. } => "Reconfigure",
        crate::EffectDef::Unattach { .. } => "Unattach",
        crate::EffectDef::PhaseOut { .. } => "PhaseOut",
        crate::EffectDef::BecomeCopyOf { .. } => "BecomeCopyOf",
        crate::EffectDef::CannotAttackUnless(..) => "CannotAttackUnless",
        crate::EffectDef::CannotAttackIf(..) => "CannotAttackIf",
        crate::EffectDef::CannotBeForcedToSacrifice => "CannotBeForcedToSacrifice",
        crate::EffectDef::CannotBeForcedToDiscard => "CannotBeForcedToDiscard",
        crate::EffectDef::ChooseColor { .. } => "ChooseColor",
        crate::EffectDef::ChangeTextBasicLandType { .. } => "ChangeTextBasicLandType",
        crate::EffectDef::SubstituteBasicLandTypeUntilEndOfTurn { .. } => {
            "SubstituteBasicLandTypeUntilEndOfTurn"
        }
        crate::EffectDef::Choose(..) => "Choose",
        crate::EffectDef::ChooseExact(..) => "ChooseExact",
        crate::EffectDef::ChooseCardsFromCollection(..) => "ChooseCardsFromCollection",
        crate::EffectDef::LookAtObjects(..) => "LookAtObjects",
        crate::EffectDef::ChooseObjectOrder(..) => "ChooseObjectOrder",
        crate::EffectDef::ChooseCards { .. } => "ChooseCards",
        crate::EffectDef::PutSpellIntoOwnersLibrary { .. } => "PutSpellIntoOwnersLibrary",
        crate::EffectDef::Counter { .. } => "Counter",
        crate::EffectDef::ClassifyObjects(..) => "ClassifyObjects",
        crate::EffectDef::RevealAndClassifyCards(..) => "RevealAndClassifyCards",
        crate::EffectDef::CombineObjects(..) => "CombineObjects",
        crate::EffectDef::BindOutput { .. } => "BindOutput",
        crate::EffectDef::ChooseOneOfEach(..) => "ChooseOneOfEach",
        crate::EffectDef::ChooseGroup(..) => "ChooseGroup",
        crate::EffectDef::SelectAtRandomFromZone { .. } => "SelectAtRandomFromZone",
        crate::EffectDef::ChooseCardName { .. } => "ChooseCardName",
        crate::EffectDef::CopyStackObject(..) => "CopyStackObject",
        crate::EffectDef::ChangeStackTargets(..) => "ChangeStackTargets",
        crate::EffectDef::CreateEmblem { .. } => "CreateEmblem",
        crate::EffectDef::CreateOngoingEffect(..) => "CreateOngoingEffect",
        crate::EffectDef::CreateToken { .. } => "CreateToken",
        crate::EffectDef::CreateAttachedToken { .. } => "CreateAttachedToken",
        crate::EffectDef::CreateMyriadTokens => "CreateMyriadTokens",
        crate::EffectDef::Endure { .. } => "Endure",
        crate::EffectDef::DealDamage(..) => "DealDamage",
        crate::EffectDef::Fight { .. } => "Fight",
        crate::EffectDef::Destroy { .. } => "Destroy",
        crate::EffectDef::Detain { .. } => "Detain",
        crate::EffectDef::Discard { .. } => "Discard",
        crate::EffectDef::DrainLife { .. } => "DrainLife",
        crate::EffectDef::DrawCards { .. } => "DrawCards",
        crate::EffectDef::ContinueReplacedDraw => "ContinueReplacedDraw",
        crate::EffectDef::EmptyManaPool { .. } => "EmptyManaPool",
        crate::EffectDef::ExileLinkedToSource { .. } => "ExileLinkedToSource",
        crate::EffectDef::PermitLookAtExiled { .. } => "PermitLookAtExiled",
        crate::EffectDef::ExileGrantingOwnerPlay { .. } => "ExileGrantingOwnerPlay",
        crate::EffectDef::ExileGrantingControllerPlayThisTurn { .. } => {
            "ExileGrantingControllerPlayThisTurn"
        }
        crate::EffectDef::ExchangeControl { .. } => "ExchangeControl",
        crate::EffectDef::GainLife { .. } => "GainLife",
        crate::EffectDef::SetLifeTotal { .. } => "SetLifeTotal",
        crate::EffectDef::IfCondition { .. } => "IfCondition",
        crate::EffectDef::IfElseCondition { .. } => "IfElseCondition",
        crate::EffectDef::IfFormat { .. } => "IfFormat",
        crate::EffectDef::SearchZonesAndExileRest { .. } => "SearchZonesAndExileRest",
        crate::EffectDef::PutIntoLibraryBeneathTop { .. } => "PutIntoLibraryBeneathTop",
        crate::EffectDef::PutSourceOntoBattlefieldAttacking => "PutSourceOntoBattlefieldAttacking",
        crate::EffectDef::VoteForPermanentToExile { .. } => "VoteForPermanentToExile",
        crate::EffectDef::BecomeMonarch { .. } => "BecomeMonarch",
        crate::EffectDef::InstallTrigger(..) => "InstallTrigger",
        crate::EffectDef::BindObjects(..) => "BindObjects",
        crate::EffectDef::IfNoObjects(..) => "IfNoObjects",
        crate::EffectDef::LandwalkCanBeBlocked(..) => "LandwalkCanBeBlocked",
        crate::EffectDef::LookAtHand { .. } => "LookAtHand",
        crate::EffectDef::LoseLife { .. } => "LoseLife",
        crate::EffectDef::LoseTheGame { .. } => "LoseTheGame",
        crate::EffectDef::WinTheGame { .. } => "WinTheGame",
        crate::EffectDef::May { .. } => "May",
        crate::EffectDef::MillUntil(..) => "MillUntil",
        crate::EffectDef::ExileFromTopUntil { .. } => "ExileFromTopUntil",
        crate::EffectDef::Cascade => "Cascade",
        crate::EffectDef::Mill { .. } => "Mill",
        crate::EffectDef::ExileTopOfLibraryToPlay { .. } => "ExileTopOfLibraryToPlay",
        crate::EffectDef::ExileTopAndMayCast { .. } => "ExileTopAndMayCast",
        crate::EffectDef::MayCastTargetWithoutPaying { .. } => "MayCastTargetWithoutPaying",
        crate::EffectDef::WithBattlefieldArrival { .. } => "WithBattlefieldArrival",
        crate::EffectDef::WithZoneMoveResult { .. } => "WithZoneMoveResult",
        crate::EffectDef::MillWhileMatching(..) => "MillWhileMatching",
        crate::EffectDef::ExileOneFromEachZone(..) => "ExileOneFromEachZone",
        crate::EffectDef::PermitCastFromGraveyardThisTurn { .. } => {
            "PermitCastFromGraveyardThisTurn"
        }
        crate::EffectDef::LookAtRandomCardInHand { .. } => "LookAtRandomCardInHand",
        crate::EffectDef::RevealAtRandomFromHand { .. } => "RevealAtRandomFromHand",
        crate::EffectDef::RevealHand { .. } => "RevealHand",
        crate::EffectDef::RemoveFromCombat { .. } => "RemoveFromCombat",
        crate::EffectDef::None => "None",
        crate::EffectDef::PayOr(..) => "PayOr",
        crate::EffectDef::ForEachInBinding { .. } => "ForEachInBinding",
        crate::EffectDef::DamageCannotBePreventedThisTurn => "DamageCannotBePreventedThisTurn",
        crate::EffectDef::PreventDamage { .. } => "PreventDamage",
        crate::EffectDef::Randomized { .. } => "Randomized",
        crate::EffectDef::FlipCoin { .. } => "FlipCoin",
        crate::EffectDef::ReduceGenericCostBy(..) => "ReduceGenericCostBy",
        crate::EffectDef::ModifyCost(..) => "ModifyCost",
        crate::EffectDef::Regenerate { .. } => "Regenerate",
        crate::EffectDef::DoubleCounters { .. } => "DoubleCounters",
        crate::EffectDef::RemoveAllCounters { .. } => "RemoveAllCounters",
        crate::EffectDef::RemoveCounters { .. } => "RemoveCounters",
        crate::EffectDef::ReplaceNextDrawThisTurn { .. } => "ReplaceNextDrawThisTurn",
        crate::EffectDef::Explore { .. } => "Explore",
        crate::EffectDef::Proliferate => "Proliferate",
        crate::EffectDef::RestartGame(..) => "RestartGame",
        crate::EffectDef::PartitionGroup(..) => "PartitionGroup",
        crate::EffectDef::RandomizeObjectOrder(..) => "RandomizeObjectOrder",
        crate::EffectDef::RevealObjects(..) => "RevealObjects",
        crate::EffectDef::MoveObjects(..) => "MoveObjects",
        crate::EffectDef::PutObjectsOntoBattlefieldFaceDown(..) => {
            "PutObjectsOntoBattlefieldFaceDown"
        }
        crate::EffectDef::ReturnLinkedExiles { .. } => "ReturnLinkedExiles",
        crate::EffectDef::ChooseForEachPlayer(..) => "ChooseForEachPlayer",
        crate::EffectDef::SacrificeOfChoice { .. } => "SacrificeOfChoice",
        crate::EffectDef::ScheduleTurnPhases(..) => "ScheduleTurnPhases",
        crate::EffectDef::SearchZone { .. } => "SearchZone",
        crate::EffectDef::Sequence(..) => "Sequence",
        crate::EffectDef::ShuffleLibrary { .. } => "ShuffleLibrary",
        crate::EffectDef::Saddle { .. } => "Saddle",
        crate::EffectDef::MayPlayWithoutPaying(..) => "MayPlayWithoutPaying",
        crate::EffectDef::SkipNextUntapSteps { .. } => "SkipNextUntapSteps",
        crate::EffectDef::Special(..) => "Special",
        crate::EffectDef::ConditionalStatic(..) => "ConditionalStatic",
        crate::EffectDef::StaticApply { .. } => "StaticApply",
        crate::EffectDef::TakeExtraTurn { .. } => "TakeExtraTurn",
        crate::EffectDef::Tap { .. } => "Tap",
        crate::EffectDef::PutOntoBattlefieldThen { .. } => "PutOntoBattlefieldThen",
        crate::EffectDef::Transform { .. } => "Transform",
        crate::EffectDef::Untap { .. } => "Untap",
    }
}

#[allow(clippy::too_many_lines)]
pub(crate) const fn predicate_kind(value: crate::ObjectPredicateDef) -> &'static str {
    match value {
        crate::ObjectPredicateDef::Any => "Any",
        crate::ObjectPredicateDef::Source => "Source",
        crate::ObjectPredicateDef::Token => "Token",
        crate::ObjectPredicateDef::Tapped => "Tapped",
        crate::ObjectPredicateDef::WasDealtDamageThisTurn => "WasDealtDamageThisTurn",
        crate::ObjectPredicateDef::DealtDamageThisTurn => "DealtDamageThisTurn",
        crate::ObjectPredicateDef::HasType(..) => "HasType",
        crate::ObjectPredicateDef::HasAnyBasicLandType(..) => "HasAnyBasicLandType",
        crate::ObjectPredicateDef::Spell => "Spell",
        crate::ObjectPredicateDef::NoncreatureSpell => "NoncreatureSpell",
        crate::ObjectPredicateDef::Ability => "Ability",
        crate::ObjectPredicateDef::ActivatedAbility => "ActivatedAbility",
        crate::ObjectPredicateDef::TriggeredAbility => "TriggeredAbility",
        crate::ObjectPredicateDef::DeclaredTargetCount { .. } => "DeclaredTargetCount",
        crate::ObjectPredicateDef::HasDeclaredTarget(..) => "HasDeclaredTarget",
        crate::ObjectPredicateDef::HasDeclaredPlayerTarget(..) => "HasDeclaredPlayerTarget",
        crate::ObjectPredicateDef::Color(..) => "Color",
        crate::ObjectPredicateDef::ColorCount(..) => "ColorCount",
        crate::ObjectPredicateDef::Subtype(..) => "Subtype",
        crate::ObjectPredicateDef::ManaValueAtMost(..) => "ManaValueAtMost",
        crate::ObjectPredicateDef::ManaValueEqualTo(..) => "ManaValueEqualTo",
        crate::ObjectPredicateDef::ManaValueAtMostValue(..) => "ManaValueAtMostValue",
        crate::ObjectPredicateDef::GenericManaCostAtMost(..) => "GenericManaCostAtMost",
        crate::ObjectPredicateDef::PowerAtLeast(..) => "PowerAtLeast",
        crate::ObjectPredicateDef::PowerExactly(..) => "PowerExactly",
        crate::ObjectPredicateDef::ToughnessExactly(..) => "ToughnessExactly",
        crate::ObjectPredicateDef::TotalPowerAndToughnessAtMost(..) => {
            "TotalPowerAndToughnessAtMost"
        }
        crate::ObjectPredicateDef::ToughnessLessThan(..) => "ToughnessLessThan",
        crate::ObjectPredicateDef::PowerGreaterThan(..) => "PowerGreaterThan",
        crate::ObjectPredicateDef::ToughnessGreaterThan(..) => "ToughnessGreaterThan",
        crate::ObjectPredicateDef::PowerLessThan(..) => "PowerLessThan",
        crate::ObjectPredicateDef::ToughnessGreaterThanItsPower => "ToughnessGreaterThanItsPower",
        crate::ObjectPredicateDef::HasCounter(..) => "HasCounter",
        crate::ObjectPredicateDef::HasAnyCounter => "HasAnyCounter",
        crate::ObjectPredicateDef::CounterCount { .. } => "CounterCount",
        crate::ObjectPredicateDef::ControlledBy(..) => "ControlledBy",
        crate::ObjectPredicateDef::OwnedBy(..) => "OwnedBy",
        crate::ObjectPredicateDef::Supertype(..) => "Supertype",
        crate::ObjectPredicateDef::DebutSet(..) => "DebutSet",
        crate::ObjectPredicateDef::NameEquals(..) => "NameEquals",
        crate::ObjectPredicateDef::NameIn(..) => "NameIn",
        crate::ObjectPredicateDef::TargetsObjectMatching(..) => "TargetsObjectMatching",
        crate::ObjectPredicateDef::HasSourcesChosenScalar(..) => "HasSourcesChosenScalar",
        crate::ObjectPredicateDef::AttackingOrBlocking => "AttackingOrBlocking",
        crate::ObjectPredicateDef::HasKeyword(..) => "HasKeyword",
        crate::ObjectPredicateDef::HasAbility(..) => "HasAbility",
        crate::ObjectPredicateDef::HasNonManaActivatedAbility => "HasNonManaActivatedAbility",
        crate::ObjectPredicateDef::Attacking => "Attacking",
        crate::ObjectPredicateDef::Saddled => "Saddled",
        crate::ObjectPredicateDef::CameUnderControlThisTurn => "CameUnderControlThisTurn",
        crate::ObjectPredicateDef::EnteredThisTurn => "EnteredThisTurn",
        crate::ObjectPredicateDef::AttachedToSource => "AttachedToSource",
        crate::ObjectPredicateDef::Blocking => "Blocking",
        crate::ObjectPredicateDef::BlockedBySource => "BlockedBySource",
        crate::ObjectPredicateDef::BlockingSource => "BlockingSource",
        crate::ObjectPredicateDef::Unpaired => "Unpaired",
        crate::ObjectPredicateDef::PairedWithSource => "PairedWithSource",
        crate::ObjectPredicateDef::BandedWithSource => "BandedWithSource",
        crate::ObjectPredicateDef::Enchanted => "Enchanted",
        crate::ObjectPredicateDef::AttachedTo(..) => "AttachedTo",
        crate::ObjectPredicateDef::AttackedThisTurn => "AttackedThisTurn",
        crate::ObjectPredicateDef::AttackedDuringControllersLastTurn => {
            "AttackedDuringControllersLastTurn"
        }
        crate::ObjectPredicateDef::All(..) => "All",
        crate::ObjectPredicateDef::AnyOf(..) => "AnyOf",
        crate::ObjectPredicateDef::Not(..) => "Not",
        crate::ObjectPredicateDef::Special(..) => "Special",
    }
}

#[allow(clippy::too_many_lines)]
pub(crate) const fn action_kind(value: crate::GameActionDef) -> &'static str {
    match value {
        crate::GameActionDef::Choice(..) => "Choice",
        crate::GameActionDef::Named { .. } => "Named",
        crate::GameActionDef::Choose(..) => "Choose",
        crate::GameActionDef::Sequence(..) => "Sequence",
        crate::GameActionDef::DiscardCards { .. } => "DiscardCards",
        crate::GameActionDef::Exile { .. } => "Exile",
        crate::GameActionDef::Sacrifice { .. } => "Sacrifice",
        crate::GameActionDef::SacrificeYours { .. } => "SacrificeYours",
        crate::GameActionDef::MoveToZone { .. } => "MoveToZone",
        crate::GameActionDef::GainControl { .. } => "GainControl",
    }
}

pub(crate) const fn prepared_predicate_kind(
    value: &crate::prepared_engine::PreparedPredicate,
) -> &'static str {
    use crate::prepared_engine::{PreparedPredicate as Plan, PreparedPredicateLeaf as Leaf};
    match value {
        Plan::All(_) => "All",
        Plan::Any(_) => "Any",
        Plan::Not(_) => "Not",
        Plan::Leaf(leaf) => match leaf {
            Leaf::Constant(_) => "Constant",
            Leaf::Source => "Source",
            Leaf::Token => "Token",
            Leaf::Tapped => "Tapped",
            Leaf::Type(_) => "Type",
            Leaf::BasicLandTypes(_) => "BasicLandTypes",
            Leaf::Color(_) => "Color",
            Leaf::ColorCount(_) => "ColorCount",
            Leaf::Subtype(_) => "Subtype",
            Leaf::Supertype(_) => "Supertype",
            Leaf::ManaValueAtMost(_) => "ManaValueAtMost",
        },
    }
}
