//! Limited Edition Beta card definitions and printings.

use super::{CardRecord, PrintingRecord, alpha};
use crate::card::{CardArt, CardRules, CardSet, cards};

pub(in crate::card::sets) static VOLCANIC_ISLAND: CardRecord = CardRecord::new(
    cards::VOLCANIC_ISLAND,
    "Volcanic Island",
    CardArt::new("0324641d-af55-4c53-b4dc-c8262e967da5", "Brian Snõddy"),
    CardSet::Beta,
    CardRules::new_land(&["Island", "Mountain"]),
);

pub(in crate::card::sets) static CARDS: &[&CardRecord] = &[&VOLCANIC_ISLAND];

pub(in crate::card::sets) static ADDITIONAL_PRINTINGS: &[PrintingRecord] = &[
    PrintingRecord::reprint(&alpha::ANKH_OF_MISHRA),
    PrintingRecord::reprint(&alpha::BLACK_VISE),
    PrintingRecord::reprint(&alpha::COPPER_TABLET),
    PrintingRecord::reprint(&alpha::FIREBALL),
    PrintingRecord::reprint(&alpha::FORK),
    PrintingRecord::reprint(&alpha::GLASSES_OF_URZA),
    PrintingRecord::reprint(&alpha::IRON_STAR),
    PrintingRecord::reprint(&alpha::LIGHTNING_BOLT),
    PrintingRecord::reprint(&alpha::MOUNTAIN),
    PrintingRecord::reprint(&alpha::RED_ELEMENTAL_BLAST),
    PrintingRecord::reprint(&alpha::SHATTER),
    PrintingRecord::reprint(&alpha::SMOKE),
    PrintingRecord::reprint(&alpha::STONE_GIANT),
    PrintingRecord::reprint(&alpha::WINTER_ORB),
    PrintingRecord::reprint(&alpha::BLACK_LOTUS),
    PrintingRecord::reprint(&alpha::CHAOS_ORB),
    PrintingRecord::reprint(&alpha::DRAGON_WHELP),
    PrintingRecord::reprint(&alpha::GOBLIN_BALLOON_BRIGADE),
    PrintingRecord::reprint(&alpha::GOBLIN_KING),
    PrintingRecord::reprint(&alpha::GRANITE_GARGOYLE),
    PrintingRecord::reprint(&alpha::IRONCLAW_ORCS),
    PrintingRecord::reprint(&alpha::MOX_EMERALD),
    PrintingRecord::reprint(&alpha::MOX_JET),
    PrintingRecord::reprint(&alpha::MOX_PEARL),
    PrintingRecord::reprint(&alpha::MOX_RUBY),
    PrintingRecord::reprint(&alpha::MOX_SAPPHIRE),
    PrintingRecord::reprint(&alpha::SOL_RING),
    PrintingRecord::reprint(&alpha::WHEEL_OF_FORTUNE),
    PrintingRecord::reprint(&alpha::JUGGERNAUT),
    PrintingRecord::reprint(&alpha::MANA_VAULT),
    PrintingRecord::reprint(&alpha::ANCESTRAL_RECALL),
    PrintingRecord::reprint(&alpha::BRAINGEYSER),
    PrintingRecord::reprint(&alpha::COUNTERSPELL),
    PrintingRecord::reprint(&alpha::DISENCHANT),
    PrintingRecord::reprint(&alpha::ISLAND),
    PrintingRecord::reprint(&alpha::JAYEMDAE_TOME),
    PrintingRecord::reprint(&alpha::PLAINS),
    PrintingRecord::reprint(&alpha::SERRA_ANGEL),
    PrintingRecord::reprint(&alpha::SWORDS_TO_PLOWSHARES),
    PrintingRecord::reprint(&alpha::TIME_WALK),
    PrintingRecord::reprint(&alpha::TUNDRA),
    PrintingRecord::reprint(&alpha::SEDGE_TROLL),
    PrintingRecord::reprint(&alpha::ARMAGEDDON),
    PrintingRecord::reprint(&alpha::BADLANDS),
    PrintingRecord::reprint(&alpha::BALANCE),
    PrintingRecord::reprint(&alpha::BAYOU),
    PrintingRecord::reprint(&alpha::BLACK_KNIGHT),
    PrintingRecord::reprint(&alpha::BIRDS_OF_PARADISE),
    PrintingRecord::reprint(&alpha::BLUE_ELEMENTAL_BLAST),
    PrintingRecord::reprint(&alpha::CHANNEL),
    PrintingRecord::reprint(&alpha::CRUSADE),
    PrintingRecord::reprint(&alpha::DARK_RITUAL),
    PrintingRecord::reprint(&alpha::DEMONIC_TUTOR),
    PrintingRecord::reprint(&alpha::DRAIN_LIFE),
    PrintingRecord::reprint(&alpha::EARTHQUAKE),
    PrintingRecord::reprint(&alpha::FOREST),
    PrintingRecord::reprint(&alpha::HYPNOTIC_SPECTER),
    PrintingRecord::reprint(&alpha::MIND_TWIST),
    PrintingRecord::reprint(&alpha::NEVINYRRALS_DISK),
    PrintingRecord::reprint(&alpha::PLATEAU),
    PrintingRecord::reprint(&alpha::PSIONIC_BLAST),
    PrintingRecord::reprint(&alpha::REGROWTH),
    PrintingRecord::reprint(&alpha::SAVANNAH),
    PrintingRecord::reprint(&alpha::SAVANNAH_LIONS),
    PrintingRecord::reprint(&alpha::SCRUBLAND),
    PrintingRecord::reprint(&alpha::SENGIR_VAMPIRE),
    PrintingRecord::reprint(&alpha::SINKHOLE),
    PrintingRecord::reprint(&alpha::SWAMP),
    PrintingRecord::reprint(&alpha::TAIGA),
    PrintingRecord::reprint(&alpha::TERROR),
    PrintingRecord::reprint(&alpha::TIME_VAULT),
    PrintingRecord::reprint(&alpha::TIMETWISTER),
    PrintingRecord::reprint(&alpha::TROPICAL_ISLAND),
    PrintingRecord::reprint(&alpha::UNDERGROUND_SEA),
    PrintingRecord::reprint(&alpha::WHITE_KNIGHT),
    PrintingRecord::reprint(&alpha::BERSERK),
    PrintingRecord::reprint(&alpha::COPY_ARTIFACT),
    PrintingRecord::reprint(&alpha::GIANT_GROWTH),
    PrintingRecord::reprint(&alpha::ICY_MANIPULATOR),
    PrintingRecord::reprint(&alpha::LLANOWAR_ELVES),
    PrintingRecord::reprint(&alpha::SCRYB_SPRITES),
    PrintingRecord::reprint(&alpha::STONE_RAIN),
    PrintingRecord::reprint(&alpha::WRATH_OF_GOD),
    PrintingRecord::alternate(&alpha::PLAINS, 1),
    PrintingRecord::alternate(&alpha::PLAINS, 2),
    PrintingRecord::alternate(&alpha::ISLAND, 1),
    PrintingRecord::alternate(&alpha::ISLAND, 2),
    PrintingRecord::alternate(&alpha::SWAMP, 1),
    PrintingRecord::alternate(&alpha::SWAMP, 2),
    PrintingRecord::alternate(&alpha::MOUNTAIN, 1),
    PrintingRecord::alternate(&alpha::MOUNTAIN, 2),
    PrintingRecord::alternate(&alpha::FOREST, 1),
    PrintingRecord::alternate(&alpha::FOREST, 2),
];
